// Auto-generated team name data from adj.json and sub.json
// Regenerate with: pnpm exec tsx scripts/generate-team-names.ts

export const ADJECTIVES = [
	"Inkless",
	"Clocked-Out",
	"Attention-Seeking",
	"Southpaw",
	"Splatsville's",
	"Big-Money",
	"Normcore",
	"Faithful",
	"Defensive",
	"Champion",
	"Royal",
	"Ammo Knights",
	"Naut Couture",
	"Man-o'-Wardrobe",
	"Crush Station",
	"Hotlantis",
	"Tableturf Battling",
	"Research-Conducting",
	"Apprentice",
	"Part-Time",
	"Go-Gettin'",
	"Overachieving",
	"Profreshional",
	"Legendary",
	"Mid-Rush",
	"High-Tide",
	"Cohock-Chargin'",
	"Foggy",
	"Low-Tide",
	"Fall-Lovin'",
	"Spring-Lovin'",
	"Winter-Lovin'",
	"Summer-Lovin'",
	"Blissed-Out",
	"Trendy",
	"Sharp-Edged",
	"Stylin'",
	"Cool",
	"Basic",
	"Traditional",
	"Trendsetting",
	"All-Natural",
	"Sizzlin'",
	"Day-Seizing",
	"Fall-Themed",
	"Spring-Fresh",
	"Captivating",
	"The",
	"Low-Rolling",
	"High-Rolling",
	"Commanding",
	"Wannabe",
	"Deadeye",
	"Reckless",
	"Chilled-Out",
	"Silent",
	"Ambidextrous",
	"Stand-Up",
	"Livestreaming",
	"Meditative",
	"Right-Handed",
	"Low-Key",
	"Pro",
	"Amateur",
	"Inkopolis Square's",
	"Inkopolis's Own",
	"Inkopolitan",
	"Feral",
	"Downtown",
	"Country-Born",
	"Greedy",
	"Trending",
	"Shortcut-Taking",
	"Fluid",
	"Optimistic",
	"Daydreamin'",
	"Clever",
	"Hungry, Hungry",
	"Competitive",
	"Slapdash",
	"Half-Hearted",
	"Early-Bird",
	"Daring",
	"Hungry",
	"Athletic",
	"Early-Morning",
	"Inkslinging",
	"Up-and-at-'Em",
	"Deep-Sea",
	"Rise-and-Shine",
	"Beachy",
	"Freewheelin'",
	"Old-Fashioned",
	"World's Best",
	"National",
	"Stormy",
	"Lonely",
	"Groundbreaking",
	"Assertive",
	"Super-Scary",
	"Vacationing",
	"Nostalgic",
	"Homecoming",
	"Hard-Workin'",
	"Sweet-Toothed",
	"Seafaring",
	"Self-Taught",
	"Summer-Breaking",
	"Processed",
	"Not-So-Fresh",
	"Salty",
	"Destined",
	"Gullible",
	"Wiped-Out",
	"Rockin'",
	"Retro",
	"Careless",
	"Avaricious",
	"Mischievous",
	"Soft",
	"Unrivaled",
	"Swole",
	"Hip",
	"Brand-New",
	"Full-Throttle",
	"Peppy",
	"Law-Breaking",
	"At-Work",
	"The First",
	"Promising",
	"Ink-Sloshing",
	"Wave-Riding",
	"Swanky",
	"Fresh-Catch",
	"Scientific",
	"Orderly",
	"The Lone",
	"Sappy",
	"Dodge-Rolling",
	"Notable",
	"Explosive",
	"Shy",
	"Calamari",
	"Fishy",
	"Puffed-Up",
	"Fuzzy",
	"The Great",
	"Birthday-Celebratin'",
	"Whimsical",
	"Dangerous",
	"Legit",
	"Dandy",
	"Ultra",
	"Floaty",
	"Indoor",
	"Ink-Covered",
	"Ink-Dripping",
	"Fresh",
	"Wicked-Fresh",
	"Stale",
	"A Simple",
	"8-Tentacled",
	"10-Tentacled",
	"Midwinter",
	"Mind-Blowing",
	"Lifelong",
	"Top-Ranked",
	"Actual",
	"Growing",
	"Studious",
	"Overpowering",
	"Spineless",
	"Headstrong",
	"Leaping",
	"Running",
	"Protective",
	"Attacking",
	"Watchful",
	"Cooperative",
	"Hidden",
	"Submersible",
	"Brute",
	"Stealthy",
	"Everyday",
	"Gaming",
	"Logical",
	"Reliable",
	"Gentle",
	"Confident",
	"Serious",
	"Mild-Mannered",
	"Cheerful",
	"High-End",
	"Chatty",
	"Cash-Stacking",
	"Absentminded",
	"Beloved",
	"Windy",
	"Watery",
	"Sneaky",
	"Fiery",
	"Incandescent",
	"Young",
	"Organized",
	"Perfect",
	"Mysterious",
	"Central",
	"Fierce",
	"Ambiguous",
	"Instantaneous",
	"Exemplary",
	"Tear-Stained",
	"Traveling",
	"Next Year's",
	"Twilight",
	"The One and Only",
	"Hibernating",
	"Sharp-Eyed",
	"Lost",
	"Procrastinating",
	"Honorary",
	"Tasteless",
	"Merciless",
	"Infinite",
	"Sleepy",
	"Time-Traveling",
	"Suave",
	"Howling",
	"Phantasmagoric",
	"Celestial",
	"Aged",
	"Lethal",
	"Secret",
	"Esoteric",
	"Exhausted",
	"Better-Than-You",
	"All-Purpose",
	"Gleaming",
	"Midday",
	"Unnoticed",
	"Unprecedented",
	"Tenacious",
	"Scorching",
	"Daytime",
	"Meaty",
	"Enigmatic",
	"Unflappable",
	"Savvy",
	"Fleeing",
	"Drained",
	"Reincarnated",
	"Sun-Dried",
	"AKA",
	"Superhuman",
	"Subterranean",
	"Massive",
	"Terrestrial",
	"Important",
	"Jumbo",
	"Oceanic",
	"Big",
	"Easygoing",
	"Ancient",
	"Multiplying",
	"Fully Automatic",
	"Glimmering",
	"Seasick",
	"Unblemished",
	"Fightin'",
	"Front-Line",
	"Endangered",
	"Persistent",
	"Sacred",
	"Local",
	"Turn-of-the-Century",
	"This Century's Best",
	"Aquarium-Bound",
	"Fan-Favorite",
	"Rising",
	"Spicy",
	"Lightning-Fast",
	"Awe-Inspiring",
	"Midnight",
	"Stark-White",
	"Deep-Red",
	"Bright-Blue",
	"Pitch-Black",
	"Woodsy",
	"Next-Generation",
	"Novice",
	"Sensational",
	"Dead-Tired",
	"Dazzling",
	"Tagalong",
	"Little",
	"Third-Eye-Opened",
	"Early-Summer",
	"Alabaster",
	"Pure",
	"Grown-Up",
	"Partying",
	"Dapper",
	"Evil",
	"Jet-Black",
	"Vindictive",
	"Self-Proclaimed",
	"Selfie-Snapping",
	"Eternity's",
	"Self-Identified",
	"Childish",
	"Job-Lovin'",
	"Late-Summer",
	"Cutting-Edge",
	"Mountain-Dwelling",
	"Picture-Taking",
	"Yesterday's",
	"Graceful",
	"First-Wave",
	"All-New",
	"The Very First",
	"The Final",
	"This Year's",
	"Limited-Edition",
	"Ever-Present",
	"Booming",
	"Crimson",
	"Steady",
	"Nosy",
	"Enlightened",
	"Aloof",
	"Hearty",
	"Artsy",
	"Flying",
	"Die-Hard",
	"Fortunate",
	"Last Year's",
	"The True Ultimate",
	"Impish",
	"Shining",
	"Forgetful",
	"Heartfelt",
	"Unarmed",
	"Sweet",
	"Sentimental",
	"Sandy",
	"Overheated",
	"Catch-of-the-Day",
	"Pool-Ready",
	"Anachronistic",
	"Supersonic",
	"Lovely",
	"Movie-Lovin'",
	"Shadowy",
	"Fated",
	"Cosmic",
	"Zipped-Lips",
	"Gone-Fishin'",
	"24-Hour",
	"Mostly",
	"Otherworldly",
	"Junior-Grade",
	"Wild",
	"A Real",
	"Lucky",
	"Seasoned",
	"Soft-and-Fluffy",
	"100%",
	"Veggie-Lovin'",
	"Fluffy",
	"Modern",
	"Lost-and-Found",
	"Won't-Lose",
	"Auspicious",
	"Innocent",
	"Miraculous",
	"Poser",
	"Comic-Lovin'",
	"Vulnerable",
	"Light",
	"Bomb-tastic",
	"Fluttering",
	"Buoyant",
	"Wibbly-Wobbly",
	"Fruit-Lovin'",
	"Dark",
	"Fragrant",
	"Fashionable",
	"Big-Time",
	"Drenched",
	"Bearded",
	"Frosty",
	"Incredible",
	"Faraway",
	"Flashy",
	"Fame-Seeking",
	"Bursting",
	"Designer-Label",
	"Swoon-Worthy",
	"Strict",
	"Slippery",
	"Painted",
	"Climactic",
	"Nameless",
	"Nice",
	"Muddy",
	"Neighborly",
	"Tidy",
	"Barbed",
	"Pointy",
	"Big Honkin'",
	"Smooth",
	"Iced",
	"Occasional",
	"Just Another",
	"Essential",
	"Diving",
	"Dynamite",
	"Overall",
	"Bargain-Binned",
	"Slim",
	"Out-of-Options",
	"Steampunky",
	"Numb",
	"Hiking",
	"Wandering",
	"Unyielding",
	"Economical",
	"Gothic",
	"Covert",
	"High-Performing",
	"Praiseworthy",
	"Arcade-Hopping",
	"Pretty Good",
	"The GOAT",
	"Glistening",
	"Sparkling",
	"Gigantified",
	"Camera-Facing",
	"Clockwork",
	"Solid",
	"Fully",
	"Unperceived",
	"Carnivorous",
	"Homebound",
	"Fish-Lovin'",
	"Sketching",
	"Precocious",
	"Easy-Peasy",
	"Made-to-Order",
	"Elegant",
	"Water-Breathing",
	"The Eternal",
	"Instant",
	"The Usual",
	"Ready-to-Go",
	"Lively",
	"Unstoppable",
	"Underground",
	"The Real Ultimate",
	"Overflowing",
	"Toon-Lovin'",
	"Splendid",
	"Warm-and-Cozy",
	"Amped-Up",
	"Outdoorsy",
	"Tech-Minded",
	"Lovable",
	"amiibo-Collecting",
	"5-Year-Planning",
	"Decade-Experienced",
	"Crab-N-Go",
	"Summer-Fun",
	"Winter-Ready",
	"Not-Streaming",
	"Daylit",
	"Dawning",
	"Realistic",
	"Lightly Snacking",
	"Late-Night",
	"Comfy-Cozy",
	"Fearful",
	"Winter-Breaking",
	"So-Called",
	"Intuitive",
	"A Complex",
	"The Original",
	"Second-Generation",
	"The Best",
	"Roaming",
	"DJ",
	"Badlands",
	"Snowy",
	"Seaside",
	"Big-Sky",
	"Dry",
	"Raw",
	"Awesome",
	"SUPERFRESH",
	"Splatoon",
	"Avant-Garde",
	"Punk",
	"Mod",
	"Goth",
	"Rockabilly",
	"Casual",
	"Sporty",
	"Breakin'",
	"Glam",
	"Vintage",
	"Bohemian",
	"Grunge",
	"Hip-Hop",
	"Thunderous",
	"Turbo",
	"Wizened",
	"Today's",
	"Virtual",
	"Half",
	"Microscopic",
	"Swift",
	"Everyone's",
	"Carefree",
	"New",
	"High-Earning",
	"Pool-Frequenting",
	"Revived",
	"Preposterous",
	"Mighty",
	"Chill",
	"Gossip-Loving",
	"Social",
	"Crafty",
	"Hopeful",
	"Sealed",
	"Theoretically Possible",
	"Rookie",
	"Sleeved",
	"World's First",
	"Nature-Loving",
	"Inflexible",
	"Prized",
	"Faux",
	"Reasonable",
	"Unfettered",
	"Unthinkable",
	"Phantom",
	"Cherished",
	"Gold",
	"Silver",
	"Undefeated",
	"New Year's",
	"This Year's Final",
	"Newly Released",
	"Tonight's",
	"Reclusive",
	"Stewed",
	"Cyber-Brainiac",
	"Magical",
	"Of-the-Moment",
	"Forevermore",
	"Anticipated",
	"Automated",
	"Drab",
	"Reflective",
	"Hoary",
	"Parallel World's",
	"Power-Concealing",
	"Nourishing",
	"Highly Nutritious",
	"Ascending",
	"Sprightly",
	"Always-in-Our-Hearts",
	"Sanguine",
	"Daybreaking",
	"Repeating",
	"Endlessly Ringing",
	"Listless",
	"In-Season",
	"Rampaging",
	"Scintillating",
	"Abyssal",
	"Originally from",
	"Unknowing",
	"Currently Obsessed with",
	"Nonstop",
	"Vivacious",
	"Aggressive",
	"Immediate",
	"Natural",
	"High-Calorie",
	"Low-Calorie",
	"Recently",
	"Esteemed",
	"Treasured",
	"Existing",
	"Nonexistent",
	"On-the-Job",
	"Choosy",
	"Delicate",
	"Haphazard",
	"Golden Egg–Like",
	"Ice-Cold",
	"Low-Battery",
	"Fully Charged",
	"Noontime",
	"Break-Time",
	"Unavailable",
	"Protecting",
	"Long-Awaited",
	"Now-Stronger",
	"Breath-Holding",
	"Genuine",
	"Nimble",
	"Movable",
	"At-Home",
	"Hometown",
	"Shooter-Using",
	"Roller-Using",
	"Charger-Using",
	"Slosher-Using",
	"Splatling-Using",
	"Dualie-Using",
	"Brella-Using",
	"Blaster-Using",
	"Brush-Using",
	"Stringer-Using",
	"Splatana-Using",
	"Replete with",
	"Watered",
	"Triumphant",
	"Tasteful",
	"Outstanding",
	"Stylish",
	"Three-Star",
	"Scheduled",
	"Trailblazing",
	"Satiating",
	"Newish",
	"Same-as-Ever",
	"Multifaceted",
	"Orthodox",
	"Regal",
	"Classic",
	"Old-School",
	"Simplistic",
	"Advanced",
	"Prototypical",
	"Sincere",
	"Flexible",
	"Creative",
	"Classy",
	"Slender",
	"Genteel",
	"Shrouded-in-Mystery",
	"Novel",
	"Brisk",
	"Undying",
	"Powerful",
	"Unwavering",
	"Heroic",
	"Swaggering",
	"Astute",
	"Pushy",
	"Resilient",
	"Burly",
	"Resourceful",
	"Lax",
	"Daredevilish",
	"Magnetic",
	"Dynamic",
	"Unique",
	"Keen-and-Nimble",
	"Cordial",
	"Dignified",
	"Flowy",
	"Cryptic",
	"High-Spirited",
	"Mind-Changing",
	"Chic",
	"Witty",
	"Cheery",
	"Vivid",
	"Rare",
	"Closed-Off",
	"Surreal",
	"Methodical",
	"Gorgeous",
	"Cute",
	"Awkward",
	"Deep",
	"Unadorned",
	"Cushy",
	"Gallant",
	"Adept",
	"Invigorating",
	"Veiled",
	"Discreet",
	"Frank",
	"Rational",
	"Charming",
	"Quiet",
	"Wise",
	"Introverted",
	"Abstract",
	"Sharp",
	"Gutsy",
	"Authentic",
	"Learned",
	"Experienced",
	"Gifted",
	"Ingenious",
	"Healthy",
	"Honest",
	"Just-Right",
	"Blustery",
	"Funky",
	"Exciting",
	"Exuberant",
	"Well-Mannered",
	"Dutiful",
	"Modest",
	"Prestigious",
	"Affable",
	"Sociable",
	"Good-Humored",
	"Urbane",
	"Meek",
	"Well-Rounded",
	"Well-Behaved",
	"Upstanding",
	"Big-Hearted",
	"Influential",
	"Mold-Breaking",
	"Ghastly",
	"Academic",
	"Plucky",
	"Cheeky",
	"Glorious",
	"Maniacal",
	"Magnificent",
	"Energetic",
	"Misplaced",
	"De Facto",
	"333x",
	"Ageless",
	"Apparent",
	"Ostensible",
	"Heart-Thumping",
	"Starchy",
	"Barely",
	"Narrowly",
	"Amusing",
	"Excited",
	"Swishy",
	"The Genuine",
	"Unnamed",
	"Glory-Hogging",
	"Prickly",
	"Lackadaisical",
	"Surviving",
	"Eccentric",
	"Idiosyncratic",
	"Rule-Breaking",
	"Snazzy",
	"Zesty",
	"Most Popular",
	"On-the-Rise",
	"Skyrocketing",
	"World-Wise",
	"Assisting",
	"Covering",
	"Bourgeois",
	"Clean",
	"Almighty",
	"Robust",
	"Enlivened",
	"Proactive",
	"Unruly",
	"Fully Committed",
	"Delightful",
	"Flower-Shaped",
	"Extraordinary",
	"Original",
	"Top-Notch",
	"Clandestine",
	"Painful",
	"Topical",
	"Lavish",
	"Thrilling",
	"Deluxe",
	"Triple",
	"Twin",
	"Double",
	"Individual",
	"Comical",
	"Imperfect",
	"Uncommon",
	"Peerless",
	"Vertebrate",
	"Expert",
	"Giant",
	"Stalwart",
	"Exquisite",
	"Acrobatic",
	"Captivated",
	"Fledgling",
	"Relaxed",
	"Playful",
	"True",
	"Candid",
	"Straightforward",
	"Unalloyed",
	"Magnanimous",
	"Stoic",
	"Angelic",
	"Single-Minded",
	"Bland",
	"Rich",
	"Earnest",
	"Forward-Plunging",
	"Total",
	"Passionate",
	"Inexorable",
	"Plain",
	"Thoughtful",
	"Frizzy",
	"Somehow",
	"Upright",
	"Peaceful",
	"Ephemeral",
	"Bright",
	"Laid-Back",
	"Dried-Out",
	"Metallic",
	"Common",
	"Nonchalant",
	"Stubborn",
	"Custom",
	"Self-Centered",
	"Determined",
	"Indomitable",
	"Unswerving",
	"Steadfast",
	"All-Out",
	"Imperative",
	"Undiscouraged",
	"Enduring",
	"Persisting",
	"Completing",
	"Piercing",
	"Hyped",
	"Climbing",
	"Proper",
	"Noteworthy",
	"Relieved",
	"Brazen",
	"Unaffected",
	"Exceptional",
	"Challenging",
	"Intellectual",
	"Fair",
	"Discerning",
	"First-Rate",
	"Strong-Willed",
	"Formidable",
	"Direct",
	"Ambitious",
	"Sturdy",
	"Dogged",
	"Dependable",
	"Meticulous",
	"Enterprising",
	"Courageous",
	"Resolved",
	"Zealous",
	"Insider",
	"Skilled",
	"Enthusiastic",
	"Wonderful",
	"Heavy-Duty",
	"Struggling",
	"Ultimate",
	"Convenient",
	"Restless",
	"Composed",
	"Comprehensible",
	"Abandoned",
	"Last",
	"Supernatural",
	"Clamorous",
	"Dense",
	"Airy",
	"My Very Own",
	"Improved",
	"Blue",
	"Ridiculous",
	"Very",
	"Really",
	"Dauntless",
	"Perpetual",
	"Recently Graduated",
	"Retirement-Age",
	"Commencing",
	"Genius",
	"Praying",
	"Sometime",
	"Occasionally",
	"Overdone",
	"Lunchtime",
	"Speciality",
	"Phoenix-Like",
	"Slacking",
	"Grateful",
	"Absolute",
	"Blatant",
	"Wistful",
	"Airborne",
	"Temporary",
	"Conspicuous",
	"Mesmerizing",
	"Bronzed",
	"Normal",
	"Lightly Seasoned",
	"Pampered",
	"Simulated",
	"Splatfest's",
	"Splatfest Battle's",
	"Rugged",
	"Grand Festival",
	"Monochrome",
	"Long-Sleeved",
	"Collab-Loving",
	"Swaggy",
	"Refreshing",
	"Simmering",
	"Positive",
	"Dim",
	"Stable",
	"Merry",
	"Ebullient",
	"Tailwind-Riding",
	"Peak-Condition",
	"Thank You for",
	"Super-Duper Lucky",
	"Super-Rare",
	"One-in-a-Million",
	"Ace",
	"Astonishing",
	"Adored",
	"Charmed",
	"Shell-Out",
	"Splatlandian",
	"Indian Ocean",
	"North Atlantic",
	"North Pacific",
	"Antarctic Ocean",
	"Arctic Ocean",
	"South Atlantic",
	"South Pacific",
	"The Shoal's Own",
	"Official-Grizzco",
	"The Crater's",
	"The City's Own",
	"Lobby-Bound",
	"Third-Gen",
	"Chaotic",
	"Midsummer",
	"Alternan",
	"Reminiscent",
	"Memversal",
	"Side Orderly",
	"Swarming",
	"Marching",
	"Battering",
	"Jelletonal",
	"Drizzling",
	"Panicking",
	"Whirling",
	"Springing",
	"Gushing",
	"Spawning",
	"Homing",
	"Towering",
	"Layered-Rotator",
	"Elusive-Bounder",
	"Intensifying-Harmony",
	"Fun",
	"The Strongest",
	"Crusty",
	"Saddle-Straddlin'",
	"Streamlined",
	"Wandercrust",
	"Tender",
	"Moving",
] as const;

export const SUBTITLES_PLURALIZED = [
	"Sploosh-o-matic Users",
	"Splattershot Jr. Users",
	"Splash-o-matic Users",
	"Aerospray Users",
	"Splattershot Users",
	".52 Gal Users",
	"N-ZAP Users",
	"Splattershot Pro Users",
	".96 Gal Users",
	"Jet Squelcher Users",
	"Luna Blaster Users",
	"Blaster Users",
	"Range Blaster Users",
	"Clash Blaster Users",
	"Rapid Blaster Users",
	"Rapid Blaster Pro Users",
	"L-3 Nozzlenose Users",
	"H-3 Nozzlenose Users",
	"Squeezer Users",
	"Carbon Roller Users",
	"Splat Roller Users",
	"Dynamo Roller Users",
	"Flingza Roller Users",
	"Inkbrush Users",
	"Octobrush Users",
	"Squiffer Users",
	"Splat Charger Users",
	"E-liter 4K Users",
	"Bamboozler 14 Users",
	"Goo Tuber Users",
	"Slosher Users",
	"Tri-Slosher Users",
	"Sloshing Machine Users",
	"Bloblobber Users",
	"Explosher Users",
	"Mini Splatling Users",
	"Heavy Splatling Users",
	"Hydra Splatling Users",
	"Ballpoint Splatling Users",
	"Nautilus Users",
	"Dapple Dualies Users",
	"Splat Dualies Users",
	"Glooga Dualies Users",
	"Dualie Squelchers Users",
	"Tetra Dualies Users",
	"Splat Brella Users",
	"Tenta Brella Users",
	"Undercover Brella Users",
	"Tri-Stringer Users",
	"Splatana Stamper Users",
	"REEF-LUX 450 Users",
	"Splatana Wiper Users",
	"Splatterscope Users",
	"E-liter 4K Scope Users",
	"Splattershot Nova Users",
	"Big Swig Roller Users",
	"Snipewriter 5H Users",
	"S-BLAST '92 Users",
	"Painbrush Users",
	"Dread Wringer Users",
	"Heavy Edit Splatling Users",
	"Douser Dualies FF Users",
	"Recycled Brella 24 Mk I Users",
	"Wellstring V Users",
	"Decavitator Users",
	"Splat Bomb Users",
	"Suction Bomb Users",
	"Burst Bomb Users",
	"Curling Bomb Users",
	"Autobomb Users",
	"Ink Mine Users",
	"Sprinkler Users",
	"Point Sensor Users",
	"Toxic Mist Users",
	"Splash Wall Users",
	"Squid Beakon Users",
	"Fizzy Bomb Users",
	"Torpedo Users",
	"Angle Shooter Users",
	"Ink Storm Users",
	"Trizooka Users",
	"Ultra Stamp Users",
	"Big Bubbler Users",
	"Inkjet Users",
	"Wave Breaker Users",
	"Zipcaster Users",
	"Reefslider Users",
	"Crab Tank Users",
	"Booyah Bomb Users",
	"Ink Vac Users",
	"Tenta Missiles Users",
	"Killer Wail 5.1 Users",
	"Triple Inkstrike Users",
	"Tacticooler Users",
	"Super Chump Users",
	"Kraken Royale Users",
	"Triple Splashdown Users",
	"Splattercolor Screen Users",
	"SquidForce Models",
	"Zink Models",
	"Krak-On Models",
	"Rockenberg Models",
	"Zekko Models",
	"Forge Models",
	"Firefin Models",
	"Skalop Models",
	"Splash Mob Models",
	"Inkline Models",
	"Tentatek Models",
	"Takoroka Models",
	"Annaki Models",
	"Enperry Models",
	"Toni Kensa Models",
	"Z+F Models",
	"Barazushi Models",
	"Emberz Models",
	"Cuttlegear Models",
	"Squid Squad Fans",
	"Chirpy Chips Fans",
	"Hightide Era Fans",
	"Wet Floor Fans",
	"Bottom Feeders Fans",
	"Ink Theory Fans",
	"SashiMori Fans",
	"Diss-Pair Fans",
	"ω-3 Fans",
	"Turquoise October Fans",
	"Dedf1sh Fans",
	"C-Side Superfans",
	"Front Roe Fans",
	"Damp Socks Fans",
	"Yoko & the Gold Bazookas Fans",
	"H2Whoa Fans",
	"Riot Act Fans",
	"Now or Never Seven Fans",
	"Hippies",
	"Barbers",
	"Double-Buns",
	"Wave Riders",
	"Pigtail Pros",
	"Headbangers",
	"Topknot Knights",
	"Sharp Dressers",
	"Buzz-Cuts",
	"Ponytails",
	"Spiked Hairs",
	"Bowl Cuts",
	"Braid Bearers",
	"Classics",
	"Wet Hairs",
	"Cornrowses",
	"Curly Hairs",
	"Punks",
	"Afros",
	"Big Curlses",
	"Fades",
	"Wanderers",
	"Greasers",
	"Hipster s",
	"Callie Fans",
	"Naut Couture Regulars",
	"Marina Fans",
	"Frye Fans",
	"Crush Station Regulars",
	"Hotlantis Regulars",
	"Squid Sisters Fans",
	"Deep Cut Fans",
	"Off the Hook Fans",
	"Pearl Fans",
	"Shiver Fans",
	"Ammo Knights Regulars",
	"Man-o'-Wardrobe Regulars",
	"Marie Fans",
	"Big Man Fans",
	"Clam Blitz Enthusiasts",
	"Splat Zones Enthusiasts",
	"Rainmaker Enthusiasts",
	"Tower Control Enthusiasts",
	"Salmon Runners",
	"Turf Warriors",
	"Story Mode Heros",
	"Clam Blitz Legends",
	"Splat Zones Legends",
	"Tower Control Legends",
	"Turf War Legends",
	"Rainmaker Legends",
	"Salmon Run Legends",
	"Story Mode Legends",
	"Inklings",
	"Octolings",
	"Tee Models",
	"Jacket Models",
	"Shirt Models",
	"Sneaker Models",
	"Knit Models",
	"Trendsetters",
	"Hat Models",
	"Glasses Models",
	"Boot Models",
	"Card Collectors",
	"Item Collectors",
	"Fashionistas",
	"Locker Rock Stars",
	"Squid Surgers",
	"Squid Rollers",
	"All-Arounders",
	"Jumpers",
	"Dodge Rollers",
	"Slow Starters",
	"Splat Bombers",
	"Guardians",
	"Raiders",
	"Manta Rays",
	"Octarians",
	"Bears",
	"Jellyfishes",
	"Humans",
	"Sea Creatures",
	"Mammals",
	"Artists",
	"Pop Stars",
	"Clock Punchers",
	"Eel Tamers",
	"Shark Tamers",
	"Clerks",
	"Office Drones",
	"Ringleaders",
	"Champs",
	"Bass Droppers",
	"Princes",
	"Princesses",
	"Brothers",
	"Sisters",
	"City Boys",
	"City Girls",
	"Grooms",
	"Brides",
	"Kings",
	"Queens",
	"Bros",
	"Sises",
	"Oden Bowls",
	"Party Lovers",
	"Surfers",
	"Festivalgoers",
	"Flowers",
	"Heat Haters",
	"Snowpersons",
	"Firecrackers",
	"Eyes of the Storm",
	"Fish",
	"Deity of Destructions",
	"Dogs",
	"Dragons",
	"Cats",
	"Dinosaurs",
	"Cephalopods",
	"Bivalves",
	"Dolphins",
	"Bookworms",
	"CEOs",
	"Assistants",
	"Athletes",
	"Agents",
	"Risk-Takers",
	"Coaches",
	"Coordinators",
	"Comedians",
	"Scientists",
	"Samurais",
	"Spies",
	"Dancers",
	"Designers",
	"Ninjas",
	"Part-Timers",
	"Pilots",
	"Hunters",
	"Planners",
	"Programmers",
	"Producers",
	"Painters",
	"Managers",
	"Models",
	"Writers",
	"Executives",
	"Astronauts",
	"Singers",
	"Presidents",
	"Vikings",
	"Students",
	"Directors",
	"Leads",
	"Anglers",
	"Assistant Managers",
	"Security Guards",
	"Researchers",
	"Authors",
	"Workers",
	"Butlers",
	"VPs",
	"Board Members",
	"Gofers",
	"Artisans",
	"Teachers",
	"Village Leaders",
	"Head Honchos",
	"Detectives",
	"Mountaineers",
	"Professors",
	"Secretaries",
	"Beauticians",
	"Middle Managers",
	"Vice Presidents",
	"Adventurers",
	"Comic Artists",
	"Heros",
	"Chefs",
	"Layabouts",
	"Big Mouths",
	"Chow Hounds",
	"Dynamos",
	"Hotheads",
	"Octoling Soldiers",
	"Power Eggs",
	"Villains",
	"Fams",
	"Turtles",
	"Forms",
	"Knights",
	"Eggs",
	"Entertainers",
	"Comrades",
	"Superheros",
	"Jokesters",
	"Magicians",
	"Brainiacs",
	"Fish Balls",
	"Materials",
	"Sushis",
	"Callers",
	"Seafood",
	"Mincemeats",
	"Squid Jerkies",
	"Booyahs",
	"Vitamins",
	"Weapons",
	"Dried Fish",
	"Muscles",
	"Illusions",
	"Shields",
	"Leaders",
	"Viewers",
	"Systems",
	"Tournament Competitors",
	"Agent 1",
	"Agent 2",
	"Agent 4",
	"Agent 8",
	"AIs",
	"Object of Affections",
	"Such and Suches",
	"Outlaws",
	"Heels",
	"Tabletop Gamers",
	"Androids",
	"Legends",
	"Squid Inks",
	"Squid Lives",
	"Squid Rings",
	"Squid, Inc.s",
	"Inks",
	"Influencers",
	"Moray Eels",
	"Elegances",
	"Big Deals",
	"Big Bosses",
	"Otakus",
	"Dance Masters",
	"Freebies",
	"Kids",
	"Pack Leaders",
	"Photographers",
	"Fried Chickens",
	"Extroverts",
	"Carpaccios",
	"Synth Players",
	"Guitarists",
	"Campers",
	"Cupids",
	"Crabs",
	"Creators",
	"Grooves",
	"Gamers",
	"Ultimate Weapons",
	"Survivalists",
	"Iconoclasts",
	"Supporters",
	"Sharks",
	"Salmon Lives",
	"Swimmers",
	"Styles",
	"Strikers",
	"Streamers",
	"Gelatins",
	"Celebs",
	"Taste Testers",
	"Title Holders",
	"Octopus Inks",
	"Octo Lives",
	"Tuna Tatakis",
	"Challengers",
	"Butterfingerses",
	"Drivers",
	"Drummers",
	"Tornados",
	"Trainers",
	"Party Animals",
	"Polyglots",
	"Rebels",
	"Workhorses",
	"Introverts",
	"Clubgoers",
	"Stand-Up Comics",
	"Fighters",
	"Mirages",
	"Planktons",
	"Brand Loyalists",
	"Freelancers",
	"Snowstorms",
	"Friends",
	"Headliners",
	"Seniors",
	"Vocalists",
	"Board Gamers",
	"Bosses",
	"Bodyguards",
	"Mermaids",
	"Masks",
	"Superstars",
	"Maniacs",
	"Mysteries",
	"Bifocal Wearers",
	"Therapists",
	"Members",
	"Lifestyles",
	"Rappers",
	"Remote Workers",
	"Rookies",
	"Robots",
	"Enthusiasts",
	"Ordinary People",
	"Lone Wolves",
	"Paupers",
	"Prodigies",
	"Monarches",
	"Hot-Spring Enjoyers",
	"Fish Finders",
	"Saltwater Fish",
	"Umibozus",
	"Cold Chills",
	"Sightseers",
	"Prime Cuts",
	"Moods",
	"Memories",
	"Demons",
	"Giants",
	"Fish Prints",
	"Mirrors",
	"Avocado Rolls",
	"Moons",
	"Fists",
	"Cavemans",
	"Experts",
	"Novices",
	"Foremans",
	"Ruffians",
	"Comic Reliefs",
	"Advisers",
	"Sashimis",
	"Legendary Warriors",
	"Underlings",
	"Senseis",
	"Free Spirits",
	"Sidekicks",
	"Fledglings",
	"Employees",
	"Greases",
	"Beginners",
	"Imps",
	"Higher-Ups",
	"Trainees",
	"Rookie of the Years",
	"Freshmans",
	"Truth Tellers",
	"Kingpins",
	"Lives of the Party",
	"Wallflowers",
	"Lives Itself",
	"Humanities",
	"Supervisors",
	"Fillets",
	"Inkantations",
	"Penny-Pinchers",
	"Mountaintop Gurus",
	"Mentors",
	"Warriors",
	"Berserkers",
	"Blade of Grasses",
	"Entities",
	"Suns",
	"Representatives",
	"Cabinet Members",
	"Freshwater Fish",
	"Group Members",
	"Style Icons",
	"Bugs",
	"Contenders",
	"Birds",
	"Stans",
	"Fisherfolks",
	"Apprentices",
	"Targets",
	"Maestros",
	"Angels",
	"Island Dwellers",
	"Tofus",
	"Foreheads",
	"Plumbers",
	"Content Creators",
	"Merpersons",
	"Sidesteppers",
	"Flotsams",
	"Subordinates",
	"Walls",
	"Predators",
	"Equations",
	"Archdemons",
	"Pros",
	"Lives",
	"Fuzzballs",
	"Actors",
	"Ghosts",
	"Atlanteans",
	"Teardrops",
	"Ronins",
	"Rice Bowls",
	"Outfits",
	"Palettes",
	"Snackses",
	"Followers",
	"Marinades",
	"Switch-Hitters",
	"Stir-Fries",
	"Catfish",
	"Grand Masters",
	"Cubs",
	"DJs",
	"Paradigms",
	"Geeks",
	"Heads",
	"Fits",
	"B-Boys",
	"B-Girls",
	"Skaters",
	"Dukes",
	"Duchesses",
	"Celebrities",
	"Mariners",
	"Fashion Designers",
	"Commanders",
	"Store Managers",
	"Patrons",
	"Sparklers",
	"Fantasy Lovers",
	"Horrorboroses",
	"Cohozunas",
	"Floats",
	"Nuances",
	"Aliens",
	"Newcomers",
	"Hopes",
	"MCs",
	"Special Attacks",
	"Special Spaces",
	"Rankers",
	"Aces in the Hole",
	"Decks",
	"Hole Cardses",
	"Test Takers",
	"Personnels",
	"Philosophers",
	"One-Hit Wonders",
	"Organizations",
	"Sleeve Collectors",
	"Rock Climbers",
	"Bungee Jumpers",
	"Soliloquys",
	"Sea-Cucumber Phones",
	"Ripples",
	"Salts",
	"Peppers",
	"Mayonnaises",
	"Seasonings",
	"Values",
	"Time Killers",
	"Clumps",
	"Repeat Customers",
	"Mushrooms",
	"Stars",
	"Talented People",
	"Superpersons",
	"Seaweeds",
	"Kelps",
	"Marine Snows",
	"Bento Boxes",
	"Fish Eggses",
	"Stews",
	"Simmered Foods",
	"Prix Fixes",
	"Curries",
	"Aficionados",
	"Informations",
	"Heart Valves",
	"Hearts",
	"Rocks",
	"Jazzes",
	"Solos",
	"Soup Stocks",
	"Soups",
	"Salads",
	"Champions",
	"Rice Balls",
	"Paradoxes",
	"Dressings",
	"Sauces",
	"Spices",
	"Specialists",
	"Specialty Shops",
	"Bandleaders",
	"Runners",
	"Speedruns",
	"Jukeboxes",
	"Demigods",
	"Laughs",
	"Theme Parks",
	"Hairstyles",
	"Encores",
	"Settlers",
	"Storms",
	"Breezes",
	"Observers",
	"Right Arms",
	"Sea Urchins",
	"Pianos",
	"Guitars",
	"Keyboards",
	"Drums",
	"Castanets",
	"Recorders",
	"Cymbalses",
	"Musical Instruments",
	"Prime Ministers",
	"Project Managers",
	"Physicians",
	"Lawyers",
	"Accountants",
	"Bodybuilders",
	"Lads",
	"Lasses",
	"Bases",
	"Sambas",
	"Machos",
	"Cool Guys",
	"Thespians",
	"Hard Workers",
	"Ship Captains",
	"Chaperones",
	"Time Travelers",
	"Puddings",
	"Counterfeits",
	"Alter Egos",
	"Grillers",
	"Smallfries",
	"Cohocks",
	"Snatchers",
	"Steelheads",
	"Steel Eels",
	"Scrappers",
	"Stingers",
	"Mawses",
	"Drizzlers",
	"Flyfishes",
	"Fish Sticks",
	"Flipper-Floppers",
	"Slammin' Lids",
	"Big Shots",
	"Goldies",
	"Motherships",
	"Mudmouths",
	"Glowflies",
	"Ranks",
	"Romanticists",
	"Steel Bodies",
	"Flavors",
	"Elites",
	"Determined Spirits",
	"Person of Influences",
	"Trailblazers",
	"Casts",
	"Aces",
	"Number Ones",
	"Foremost Figures",
	"Mainstays",
	"Emperors",
	"Paragons",
	"Intermediaries",
	"Prototypes",
	"Schemers",
	"Brave Warriors",
	"Person of Cultures",
	"Honor Students",
	"Brains",
	"Trappers",
	"Intellectuals",
	"Impractical Theories",
	"Dislikes",
	"Meisters",
	"Governors",
	"Office Chiefs",
	"Caretakers",
	"Bank Presidents",
	"Harlequins",
	"Focal Points",
	"Event Organizers",
	"VIPs",
	"Performers",
	"Woodcutters",
	"Sous-Chefs",
	"Engineers",
	"Contractors",
	"Prosperous Merchants",
	"Referees",
	"Manila Clams",
	"Concierges",
	"Tentacles",
	"Nobles",
	"Temps",
	"Pranksters",
	"Great Regents",
	"Main Characters",
	"Leading Actors",
	"Leading Actresses",
	"Dark Horses",
	"Key Figures",
	"Masterminds",
	"Tacticians",
	"Vagabonds",
	"Voyagers",
	"Wandering Hermits",
	"Nomads",
	"Bounty Hunters",
	"Timeline Jumpers",
	"Generations",
	"Elders",
	"Captains",
	"Guests",
	"String Pullers",
	"Galleries",
	"Big Names",
	"Regular Customers",
	"Partners",
	"Cyborgs",
	"Successes",
	"Shadow Commanders",
	"Helpers",
	"Backers",
	"Millionaires",
	"Custodians",
	"Lieutenants",
	"Origins",
	"Czars",
	"Cheer Teams",
	"Staffs",
	"Factotums",
	"Energies",
	"Engines",
	"Consultants",
	"Tutors",
	"Puppet Masters",
	"Buddies",
	"Critics",
	"Luck Pushers",
	"Teams",
	"Buffoons",
	"Players",
	"TV Personalities",
	"Announcers",
	"Geniuses",
	"Golfers",
	"Batters",
	"Pitchers",
	"Catchers",
	"Benchwarmers",
	"Virtuosos",
	"Conductors",
	"Musical Performers",
	"Lyricists",
	"Pianists",
	"Ingenues",
	"Narrators",
	"Pro Wrestlers",
	"Sprinters",
	"Boxers",
	"Extras",
	"Cinematographers",
	"Stunt Performers",
	"Descendants",
	"Offsprings",
	"Sponsors",
	"Suggestions",
	"Facilitators",
	"Showstoppers",
	"Possessors",
	"Housekeepers",
	"Traders",
	"Fortune Tellers",
	"Globe-Trotters",
	"Pinch Hitters",
	"Leadoff Hitters",
	"Musketeers",
	"Crowds",
	"Circles",
	"Flocks",
	"Cooperators",
	"Units",
	"Armies",
	"Coteries",
	"Quartets",
	"Choruses",
	"Podium Finishers",
	"Guilds",
	"Groups",
	"Horses",
	"Rabbits",
	"Pandas",
	"Koalas",
	"Squirrels",
	"Sea Otters",
	"Elephants",
	"Giraffes",
	"Whales",
	"Tigers",
	"Lions",
	"Hamsters",
	"Deer",
	"Bookkeepers",
	"Idea People",
	"Rock 'n' Rollers",
	"Controllers",
	"Storytellers",
	"Illustrators",
	"Finger Painters",
	"Scriveners",
	"Founders",
	"Families",
	"Craftsmans",
	"Machines",
	"Navigators",
	"Inventors",
	"Parties",
	"Playmakers",
	"Young Leaders",
	"Mascots",
	"Fairies",
	"Joke Tellers",
	"Voice Actors",
	"Learners",
	"Tenderfoots",
	"Heads of the Class",
	"University Students",
	"Architects",
	"Costumiers",
	"Ferocious Fighters",
	"Knowledgeable People",
	"Lofty Dreams",
	"Wizes",
	"Prominent Figures",
	"Grapplers",
	"Natural Enemies",
	"Horseshoe Crabs",
	"Pond Snails",
	"Nautiluses",
	"Coconut Crabs",
	"Sea Anemones",
	"Goldfish",
	"Horse Mackerels",
	"Devil Rays",
	"Sea Slugs",
	"Shrimp",
	"Spider Crabs",
	"Rivals",
	"Weaknesses",
	"Types",
	"Sweethearts",
	"Imitations",
	"Processes",
	"Gatherings",
	"Shoals",
	"Crews",
	"Beasts",
	"Rulers",
	"Fossils",
	"Wardens",
	"Collectors",
	"Crushes",
	"Souls",
	"State of Minds",
	"Marathons",
	"Good People",
	"Clients",
	"Dolls",
	"Noble Scions",
	"Protagonists",
	"Symbols",
	"Authorities",
	"Contributors",
	"Cartoon Characters",
	"Plushies",
	"Spirits",
	"Thoroughbreds",
	"Person of Notes",
	"Professionals",
	"Gourmets",
	"Sumo Wrestlers",
	"Family Trees",
	"Soldiers",
	"Order of Knightses",
	"Victors",
	"Villagers",
	"School Principals",
	"Protectors",
	"Explorers",
	"Seekers",
	"Pugilists",
	"Paladins",
	"Door Guards",
	"Rangers",
	"Monks",
	"Sages",
	"Doctors",
	"Blacksmiths",
	"Postdocs",
	"Dignitaries",
	"Artistes",
	"Interns",
	"Alchemists",
	"Security Details",
	"Ores",
	"Guides",
	"Chauffeurs",
	"Bloggers",
	"Operators",
	"Librarians",
	"Objet d'Arts",
	"Successors",
	"Owners",
	"Proxies",
	"Pupils",
	"Disciples",
	"Scholars",
	"Graduates",
	"Collegians",
	"PhD Candidates",
	"Ketchups",
	"Bamboo Shoots",
	"Pops",
	"Psychics",
	"Arbiters",
	"Litterateurs",
	"Megalodontias",
	"Recollections",
	"Stylists",
	"Entrepreneurs",
	"Musicians",
	"Party Stars",
	"Mercenaries",
	"Alliances",
	"Bards",
	"Otherworldly Beings",
	"Chaoses",
	"Noobs",
	"Vanguards",
	"Luminaries",
	"Playings",
	"Lucky Ducks",
	"Protected Specieses",
	"Chosen Ones",
	"Gadabouts",
	"Point Guards",
	"Optimists",
	"Daredevils",
	"Prizewinners",
	"Youths",
	"Squid",
	"Octopuses",
	"Salmon",
	"Boys",
	"Girls",
	"Agent 3",
	"Fathers",
	"Mothers",
	"Dads",
	"Moms",
	"Sons",
	"Daughters",
	"Big Brothers",
	"Big Sisters",
	"Little Brothers",
	"Little Sisters",
	"Grandpas",
	"Grandmas",
	"Grandchilds",
	"Uncles",
	"Aunts",
	"Youngsters",
	"Pets",
	"World Champs",
	"Mediators",
	"Beta Testers",
	"Revelers",
	"Languendos",
	"Andantes",
	"Lentos",
	"Portals",
	"Capricciosos",
	"Alla Mambos",
	"Accelerandos",
	"Spiccatos",
	"Trionfales",
	"Accordos",
	"Arpeggios",
	"Nobilmentes",
	"Asynchronous Rondos",
	"Pinging Marciales",
	"Parallel Canons",
	"Tableturf Battlers",
	"Card Gamers",
	"Travelers",
	"Cyclists",
	"Tempuras",
	"Boosters",
	"Resiliences",
	"Finales",
] as const;
