export const weaponParams = {
	baseWeaponStats: {
		"0": {
			Range_SpawnSpeed: 2.06,
			Range_GoStraightStateEndMaxSpeed: 1.835,
			Range_GoStraightToBrakeStateFrame: 2,
			Range_FreeGravity: 0.016,
			Range_ZRate: 2,
			WeaponSpeedType: "Fast",
			MoveSpeed: 0.08,
			DamageParam_ValueMax: 380,
			DamageParam_ValueMin: 190,
			Jump_DegSwerve: 17.49,
			Stand_DegSwerve: 11.66,
			InkRecoverStop: 15,
			InkConsume: 0.008,
		},
		"10": {
			Range_SpawnSpeed: 2.266,
			Range_GoStraightStateEndMaxSpeed: 1.9513,
			Range_GoStraightToBrakeStateFrame: 3,
			Range_FreeGravity: 0.016,
			Range_ZRate: 2,
			WeaponSpeedType: "Fast",
			MoveSpeed: 0.076,
			DamageParam_ValueMax: 280,
			DamageParam_ValueMin: 140,
			Jump_DegSwerve: 14.58,
			Stand_DegSwerve: 11.66,
			InkRecoverStop: 15,
			InkConsume: 0.0043,
		},
		"20": {
			Range_SpawnSpeed: 4.0376,
			Range_GoStraightStateEndMaxSpeed: 1.6289,
			Range_GoStraightToBrakeStateFrame: 2,
			Range_FreeGravity: 0.016,
			Range_ZRate: 2,
			WeaponSpeedType: "Fast",
			MoveSpeed: 0.072,
			DamageParam_ValueMax: 280,
			DamageParam_ValueMin: 140,
			Jump_DegSwerve: 0,
			Stand_DegSwerve: 0,
			InkConsume: 0.008,
		},
		"30": {
			Range_SpawnSpeed: 2.266,
			Range_GoStraightStateEndMaxSpeed: 1.9513,
			Range_GoStraightToBrakeStateFrame: 3,
			Range_FreeGravity: 0.016,
			Range_ZRate: 2,
			WeaponSpeedType: "Fast",
			MoveSpeed: 0.072,
			DamageParam_ValueMax: 240,
			DamageParam_ValueMin: 120,
			Jump_DegSwerve: 15.54,
			Stand_DegSwerve: 12.63,
			InkRecoverStop: 15,
			InkConsume: 0.005,
		},
		"40": {
			Range_SpawnSpeed: 2.266,
			Range_GoStraightStateEndMaxSpeed: 1.493,
			Range_GoStraightToBrakeStateFrame: 4,
			Range_FreeGravity: 0.016,
			Range_ZRate: 2,
			MoveSpeed: 0.072,
			DamageParam_ValueMax: 360,
			DamageParam_ValueMin: 180,
			Jump_DegSwerve: 11.66,
			Stand_DegSwerve: 4.86,
			InkConsume: 0.0092,
		},
		"50": {
			Range_SpawnSpeed: 3.06,
			Range_GoStraightStateEndMaxSpeed: 1.667,
			Range_GoStraightToBrakeStateFrame: 3,
			Range_FreeGravity: 0.016,
			Range_ZRate: 2,
			MoveSpeed: 0.06,
			DamageParam_ValueMax: 520,
			DamageParam_ValueMin: 300,
			Jump_DegSwerve: 12,
			Stand_DegSwerve: 6,
			InkConsume: 0.015,
		},
		"60": {
			Range_SpawnSpeed: 2.2,
			Range_GoStraightStateEndMaxSpeed: 1.4495,
			Range_GoStraightToBrakeStateFrame: 4,
			Range_FreeGravity: 0.016,
			Range_ZRate: 2,
			WeaponSpeedType: "Fast",
			MoveSpeed: 0.088,
			DamageParam_ValueMax: 300,
			DamageParam_ValueMin: 150,
			Jump_DegSwerve: 12,
			Stand_DegSwerve: 4.75,
			InkConsume: 0.008,
		},
		"70": {
			overwrites: {
				ConsumeRt_Main: {
					High: 0.5,
					Mid: 0.7,
				},
			},
			Range_SpawnSpeed: 3.833333,
			Range_GoStraightStateEndMaxSpeed: 2.2698,
			Range_GoStraightToBrakeStateFrame: 3,
			Range_FreeGravity: 0.016,
			Range_ZRate: 2,
			MoveSpeed: 0.055,
			DamageParam_ValueMax: 450,
			DamageParam_ValueMin: 225,
			Jump_DegSwerve: 6,
			Stand_DegSwerve: 2.5,
			InkConsume: 0.02,
		},
		"80": {
			Range_SpawnSpeed: 2.45,
			Range_GoStraightStateEndMaxSpeed: 2.377,
			Range_GoStraightToBrakeStateFrame: 5,
			Range_FreeGravity: 0.016,
			Range_ZRate: 2,
			MoveSpeed: 0.04,
			DamageParam_ValueMax: 620,
			DamageParam_ValueMin: 350,
			Jump_DegSwerve: 11.3511,
			Stand_DegSwerve: 4,
			InkConsume: 0.023,
		},
		"90": {
			Range_SpawnSpeed: 3.36,
			Range_GoStraightStateEndMaxSpeed: 2.232,
			Range_GoStraightToBrakeStateFrame: 5,
			Range_FreeGravity: 0.016,
			Range_ZRate: 2,
			MoveSpeed: 0.06,
			DamageParam_ValueMax: 320,
			DamageParam_ValueMin: 160,
			Jump_DegSwerve: 8,
			Stand_DegSwerve: 2.5,
			InkConsume: 0.016,
		},
		"100": {
			Range_SpawnSpeed: 2.2,
			Range_GoStraightStateEndMaxSpeed: 2.2698,
			Range_GoStraightToBrakeStateFrame: 5,
			Range_FreeGravity: 0.016,
			Range_ZRate: 2,
			MoveSpeed: 0.079,
			DamageParam_ValueMax: 240,
			DamageParam_ValueMin: 120,
			Jump_DegSwerve: 8,
			Stand_DegSwerve: 4.5,
			InkConsume: 0.0096,
		},
		"200": {
			overwrites: {
				ConsumeRt_Main: {
					High: 0.5,
					Mid: 0.7,
				},
				ReduceJumpSwerveRate: {
					Mid: 0.625,
				},
			},
			Range_SpawnSpeed: 0.87,
			Range_GoStraightStateEndMaxSpeed: 0.8484,
			Range_GoStraightToBrakeStateFrame: 7,
			Range_FreeGravity: 0.016,
			Range_ZRate: 2,
			BlastRadius: 4,
			WeaponSpeedType: "Fast",
			MoveSpeed: 0.05,
			DamageParam_ValueDirect: 1250,
			BlastParam_DistanceDamage: [
				{
					Damage: 700,
					Distance: 1.8,
				},
				{
					Damage: 500,
					Distance: 4,
				},
			],
			Jump_DegSwerve: 6,
			Stand_DegSwerve: 0,
			InkRecoverStop: 55,
			InkConsume: 0.075,
		},
		"210": {
			overwrites: {
				ReduceJumpSwerveRate: {
					Mid: 0.5,
				},
			},
			Range_SpawnSpeed: 0.945,
			Range_GoStraightStateEndMaxSpeed: 0.9131,
			Range_GoStraightToBrakeStateFrame: 9,
			Range_FreeGravity: 0.016,
			Range_ZRate: 2,
			BlastRadius: 3.47,
			MoveSpeed: 0.045,
			DamageParam_ValueDirect: 1250,
			BlastParam_DistanceDamage: [
				{
					Damage: 700,
					Distance: 1.11,
				},
				{
					Damage: 500,
					Distance: 3.47,
				},
			],
			Jump_DegSwerve: 10,
			Stand_DegSwerve: 0,
			InkRecoverStop: 57,
			InkConsume: 0.1,
		},
		"220": {
			overwrites: {
				ReduceJumpSwerveRate: {
					Mid: 0.5,
				},
			},
			Range_SpawnSpeed: 1.08,
			Range_GoStraightStateEndMaxSpeed: 1.0073,
			Range_GoStraightToBrakeStateFrame: 11,
			Range_FreeGravity: 0.016,
			Range_ZRate: 2,
			BlastRadius: 3.37,
			MoveSpeed: 0.04,
			DamageParam_ValueDirect: 1250,
			BlastParam_DistanceDamage: [
				{
					Damage: 700,
					Distance: 1.01,
				},
				{
					Damage: 500,
					Distance: 3.37,
				},
			],
			Jump_DegSwerve: 8,
			Stand_DegSwerve: 0,
			InkRecoverStop: 70,
			InkConsume: 0.11,
		},
		"230": {
			overwrites: {
				ReduceJumpSwerveRate: {
					Mid: 0.5,
				},
			},
			Range_SpawnSpeed: 0.935,
			Range_GoStraightStateEndMaxSpeed: 0.92715,
			Range_GoStraightToBrakeStateFrame: 8,
			Range_FreeGravity: 0.016,
			Range_ZRate: 2,
			BlastRadius: 4.17,
			WeaponSpeedType: "Fast",
			MoveSpeed: 0.068,
			DamageParam_ValueDirect: 600,
			BlastParam_DistanceDamage: [
				{
					Damage: 300,
					Distance: 1.17,
				},
				{
					Damage: 300,
					Distance: 4.17,
				},
			],
			Jump_DegSwerve: 8,
			Stand_DegSwerve: 0,
			InkRecoverStop: 40,
			InkConsume: 0.04,
		},
		"240": {
			overwrites: {
				ReduceJumpSwerveRate: {
					Mid: 0.5,
				},
			},
			Range_SpawnSpeed: 1.2,
			Range_GoStraightStateEndMaxSpeed: 1.13305,
			Range_GoStraightToBrakeStateFrame: 11,
			Range_FreeGravity: 0.016,
			Range_ZRate: 2,
			BlastRadius: 3.37,
			MoveSpeed: 0.055,
			DamageParam_ValueDirect: 850,
			BlastParam_DistanceDamage: [
				{
					Damage: 350,
					Distance: 1.01,
				},
				{
					Damage: 350,
					Distance: 3.37,
				},
			],
			Jump_DegSwerve: 8,
			Stand_DegSwerve: 0,
			InkRecoverStop: 47,
			InkConsume: 0.07,
		},
		"250": {
			overwrites: {
				ReduceJumpSwerveRate: {
					Mid: 0.5,
				},
			},
			Range_SpawnSpeed: 1.4,
			Range_GoStraightStateEndMaxSpeed: 1.3426,
			Range_GoStraightToBrakeStateFrame: 11,
			Range_FreeGravity: 0.016,
			Range_ZRate: 2,
			BlastRadius: 3.35,
			MoveSpeed: 0.05,
			DamageParam_ValueDirect: 850,
			BlastParam_DistanceDamage: [
				{
					Damage: 350,
					Distance: 0.99,
				},
				{
					Damage: 350,
					Distance: 3.35,
				},
			],
			Jump_DegSwerve: 8,
			Stand_DegSwerve: 0,
			InkRecoverStop: 50,
			InkConsume: 0.0912,
		},
		"260": {
			overwrites: {
				ReduceJumpSwerveRate: {
					Mid: 0.625,
				},
			},
			Range_SpawnSpeed: 1.7,
			Range_GoStraightStateEndMaxSpeed: 1.65,
			Range_GoStraightToBrakeStateFrame: 7,
			Range_FreeGravity: 0.016,
			Range_ZRate: 2,
			BlastRadius: 2.07,
			MoveSpeed: 0.04,
			DamageParam_ValueDirect: 1250,
			BlastParam_DistanceDamage: [
				{
					Damage: 700,
					Distance: 1.07,
				},
				{
					Damage: 500,
					Distance: 2.07,
				},
			],
			Jump_DegSwerve: 8,
			Stand_DegSwerve: 0,
			InkRecoverStop: 60,
			InkConsume: 0.095,
		},
		"300": {
			Range_SpawnSpeed: 3.413,
			Range_GoStraightStateEndMaxSpeed: 1.946,
			Range_GoStraightToBrakeStateFrame: 3,
			Range_ZRate: 2,
			TripleShotSpanFrame: 8,
			MoveSpeed: 0.08,
			DamageParam_ValueMax: 310,
			DamageParam_ValueMin: 155,
			Jump_DegSwerve: 6,
			Stand_DegSwerve: 1,
			InkRecoverStop: 25,
			InkConsume: 0.011,
		},
		"310": {
			overwrites: {
				ConsumeRt_Main: {
					High: 0.5,
					Mid: 0.7,
				},
			},
			Range_SpawnSpeed: 2.875,
			Range_GoStraightStateEndMaxSpeed: 2.2698,
			Range_GoStraightToBrakeStateFrame: 4,
			Range_ZRate: 2,
			TripleShotSpanFrame: 20,
			MoveSpeed: 0.06,
			DamageParam_ValueMax: 450,
			DamageParam_ValueMin: 225,
			Jump_DegSwerve: 1,
			Stand_DegSwerve: 1,
			InkRecoverStop: 25,
			InkConsume: 0.0208,
		},
		"400": {
			Range_SpawnSpeed: 3.05,
			Range_GoStraightStateEndMaxSpeed: 2.8303,
			Range_GoStraightToBrakeStateFrame: 4,
			Range_FreeGravity: 0.016,
			Range_ZRate: 2,
			MoveSpeed: 0.066,
			DamageParam_ValueMax: 380,
			DamageParam_ValueMin: 190,
			Variable_Damage_ValueMax: 300,
			Variable_Damage_ValueMin: 150,
			Jump_DegSwerve: 0,
			Stand_DegSwerve: 0,
			Variable_Jump_DegSwerve: 13,
			Variable_Stand_DegSwerve: 8,
			InkConsume: 0.024,
		},
		"1000": {
			Range_SpawnSpeed: 1.5166,
			Range_GoStraightToBrakeStateFrame: 6,
			Range_FreeGravity: 0.04,
			Range_FreeAirResist: 0.1,
			Range_ZRate: 2,
			WeaponSpeedType: "Fast",
			BodyParam_Damage: 700,
			VerticalSwingUnitGroupParam_DamageParam_DamageMinValue: 350,
			VerticalSwingUnitGroupParam_DamageParam_DamageMaxValue: 1200,
			WideSwingUnitGroupParam_DamageParam_DamageMinValue: 250,
			WideSwingUnitGroupParam_DamageParam_DamageMaxValue: 1000,
			InkConsume_WeaponSwingParam: 0.0396,
		},
		"1010": {
			Range_SpawnSpeed: 1.8338,
			Range_GoStraightToBrakeStateFrame: 6,
			Range_FreeGravity: 0.04,
			Range_FreeAirResist: 0.1,
			Range_ZRate: 2,
			BodyParam_Damage: 1250,
			VerticalSwingUnitGroupParam_DamageParam_DamageMinValue: 400,
			VerticalSwingUnitGroupParam_DamageParam_DamageMaxValue: 1500,
			WideSwingUnitGroupParam_DamageParam_DamageMinValue: 350,
			WideSwingUnitGroupParam_DamageParam_DamageMaxValue: 1500,
			InkConsume_WeaponSwingParam: 0.085,
		},
		"1020": {
			overwrites: {
				ConsumeRt_Main: {
					High: 0.5,
					Mid: 0.7,
				},
			},
			Range_SpawnSpeed: 2.0289,
			Range_GoStraightToBrakeStateFrame: 9,
			Range_FreeGravity: 0.04,
			Range_FreeAirResist: 0.1,
			Range_ZRate: 2,
			WeaponSpeedType: "Slow",
			BodyParam_Damage: 1250,
			VerticalSwingUnitGroupParam_DamageParam_DamageMinValue: 400,
			VerticalSwingUnitGroupParam_DamageParam_DamageMaxValue: 1800,
			WideSwingUnitGroupParam_DamageParam_DamageMinValue: 400,
			WideSwingUnitGroupParam_DamageParam_DamageMaxValue: 1800,
			InkConsume_WeaponSwingParam: 0.21,
		},
		"1030": {
			Range_SpawnSpeed: 1.7026,
			Range_GoStraightToBrakeStateFrame: 9,
			Range_FreeGravity: 0.04,
			Range_FreeAirResist: 0.1,
			Range_ZRate: 2,
			BodyParam_Damage: 1250,
			VerticalSwingUnitGroupParam_DamageParam_DamageMinValue: 400,
			VerticalSwingUnitGroupParam_DamageParam_DamageMaxValue: 1500,
			WideSwingUnitGroupParam_DamageParam_DamageMinValue: 300,
			WideSwingUnitGroupParam_DamageParam_DamageMaxValue: 1500,
			InkConsume_WeaponVerticalSwingParam: 0.12,
			InkConsume_WeaponWideSwingParam: 0.08,
		},
		"1040": {
			Range_SpawnSpeed: 2.2749,
			Range_GoStraightToBrakeStateFrame: 6,
			Range_FreeGravity: 0.04,
			Range_FreeAirResist: 0.1,
			Range_ZRate: 2,
			BodyParam_Damage: 700,
			VerticalSwingUnitGroupParam_DamageParam_DamageMinValue: 400,
			VerticalSwingUnitGroupParam_DamageParam_DamageMaxValue: 1200,
			WideSwingUnitGroupParam_DamageParam_DamageMinValue: 400,
			WideSwingUnitGroupParam_DamageParam_DamageMaxValue: 700,
			InkConsume_WeaponSwingParam: 0.09,
		},
		"1100": {
			Range_SpawnSpeed: 0.72,
			Range_GoStraightToBrakeStateFrame: 7,
			Range_ZRate: 2,
			WeaponSpeedType: "Fast",
			BodyParam_Damage: 200,
			SwingUnitGroupParam_DamageParam_DamageMinValue: 150,
			SwingUnitGroupParam_DamageParam_DamageMaxValue: 300,
			InkConsume_WeaponSwingParam: 0.02,
		},
		"1110": {
			Range_SpawnSpeed: 0.84,
			Range_GoStraightToBrakeStateFrame: 8,
			Range_ZRate: 2,
			BodyParam_Damage: 250,
			SwingUnitGroupParam_DamageParam_DamageMinValue: 200,
			SwingUnitGroupParam_DamageParam_DamageMaxValue: 400,
			InkConsume_WeaponSwingParam: 0.03,
		},
		"1120": {
			Range_SpawnSpeed: 1.05,
			Range_GoStraightToBrakeStateFrame: 9,
			Range_ZRate: 2,
			BodyParam_Damage: 300,
			SwingUnitGroupParam_DamageParam_DamageMinValue: 310,
			SwingUnitGroupParam_DamageParam_DamageMaxValue: 600,
			InkConsume_WeaponSwingParam: 0.048,
		},
		"2000": {
			DistanceFullCharge: 16.765,
			DistanceMaxCharge: 16.765,
			DistanceMinCharge: 9.261,
			MoveSpeedFullCharge: 0.03,
			DamageParam_ValueFullCharge: 1400,
			DamageParam_ValueMaxCharge: 800,
			DamageParam_ValueMinCharge: 400,
			ChargeFrameFullCharge: 45,
			KeepChargeFullFrame: 75,
			InkConsumeFullCharge: 0.105,
			InkConsumeMinCharge: 0.018667,
		},
		"2010": {
			DistanceFullCharge: 24.037,
			DistanceMaxCharge: 24.037,
			DistanceMinCharge: 9.033,
			MoveSpeedFullCharge: 0.02,
			DamageParam_ValueFullCharge: 1600,
			DamageParam_ValueMaxCharge: 800,
			DamageParam_ValueMinCharge: 400,
			KeepChargeFullFrame: 75,
			InkConsumeFullCharge: 0.18,
			InkConsumeMinCharge: 0.0225,
		},
		"2020": {
			DistanceFullCharge: 26.037,
			DistanceMaxCharge: 24.037,
			DistanceMinCharge: 9.033,
			MoveSpeedFullCharge: 0.02,
			DamageParam_ValueFullCharge: 1600,
			DamageParam_ValueMaxCharge: 800,
			DamageParam_ValueMinCharge: 400,
			InkConsumeFullCharge: 0.18,
			InkConsumeMinCharge: 0.0225,
		},
		"2030": {
			overwrites: {
				ConsumeRt_Main: {
					High: 0.5,
					Mid: 0.7,
				},
			},
			DistanceFullCharge: 29.05,
			DistanceMaxCharge: 29.05,
			DistanceMinCharge: 9.045,
			WeaponSpeedType: "Slow",
			MoveSpeedFullCharge: 0.015,
			DamageParam_ValueFullCharge: 1800,
			DamageParam_ValueMaxCharge: 800,
			DamageParam_ValueMinCharge: 400,
			ChargeFrameFullCharge: 92,
			KeepChargeFullFrame: 75,
			InkConsumeFullCharge: 0.25,
			InkConsumeMinCharge: 0.0225,
		},
		"2040": {
			overwrites: {
				ConsumeRt_Main: {
					High: 0.5,
					Mid: 0.7,
				},
			},
			DistanceFullCharge: 31.05,
			DistanceMaxCharge: 29.05,
			DistanceMinCharge: 9.045,
			WeaponSpeedType: "Slow",
			MoveSpeedFullCharge: 0.015,
			DamageParam_ValueFullCharge: 1800,
			DamageParam_ValueMaxCharge: 800,
			DamageParam_ValueMinCharge: 400,
			ChargeFrameFullCharge: 92,
			InkConsumeFullCharge: 0.25,
			InkConsumeMinCharge: 0.0225,
		},
		"2050": {
			DistanceFullCharge: 19.564,
			DistanceMaxCharge: 19.564,
			DistanceMinCharge: 19.564,
			WeaponSpeedType: "Fast",
			MoveSpeedFullCharge: 0.06,
			DamageParam_ValueFullCharge: 850,
			DamageParam_ValueMaxCharge: 850,
			DamageParam_ValueMinCharge: 300,
			ChargeFrameFullCharge: 20,
			InkConsumeFullCharge: 0.07,
			InkConsumeMinCharge: 0.028,
		},
		"2060": {
			DistanceFullCharge: 19.804,
			DistanceMaxCharge: 18.804,
			DistanceMinCharge: 12.602,
			MoveSpeedFullCharge: 0.03,
			DamageParam_ValueFullCharge: 1800,
			DamageParam_ValueMaxCharge: 1300,
			DamageParam_ValueMinCharge: 400,
			ChargeFrameFullCharge: 71,
			KeepChargeFullFrame: 300,
			InkConsumeFullCharge: 0.15,
			InkConsumeMinCharge: 0.02,
		},
		"2070": {
			DistanceFullCharge: 26.037,
			DistanceMaxCharge: 24.037,
			DistanceMinCharge: 9.033,
			MoveSpeedFullCharge: 0.068,
			DamageParam_ValueFullCharge: 680,
			DamageParam_ValueMaxCharge: 680,
			DamageParam_ValueMinCharge: 400,
			ChargeFrameFullCharge: 72,
			InkRecoverStop: 20,
			InkConsumeFullCharge: 0.35,
			InkConsumeMinCharge: 0.0197,
		},
		"3000": {
			Range_SpawnSpeed: 1.7609,
			Range_GoStraightStateEndMaxSpeed: 10,
			Range_GoStraightToBrakeStateFrame: 2,
			Range_FreeGravity: 0.05,
			Range_BrakeAirResist: 0.1,
			Range_BrakeGravity: 0.04,
			Range_BrakeToFreeStateFrame: 1,
			Range_ZRate: 2,
			MoveSpeed: 0.04,
			DamageParam_ValueDirectMax: 700,
			DamageParam_ValueDirectMin: 500,
			InkRecoverStop: 40,
			InkConsumeSlosher: 0.076,
		},
		"3010": {
			Range_SpawnSpeed: 1.2229,
			Range_GoStraightStateEndMaxSpeed: 10,
			Range_GoStraightToBrakeStateFrame: 3,
			Range_FreeGravity: 0.05,
			Range_BrakeAirResist: 0.1,
			Range_BrakeGravity: 0.04,
			Range_BrakeToFreeStateFrame: 1,
			Range_ZRate: 2,
			WeaponSpeedType: "Fast",
			MoveSpeed: 0.066,
			DamageParam_ValueDirectMax: 620,
			DamageParam_ValueDirectMin: 350,
			InkRecoverStop: 35,
			InkConsumeSlosher: 0.06,
		},
		"3020": {
			Range_SpawnSpeed: 1.4737,
			Range_GoStraightStateEndMaxSpeed: 10,
			Range_GoStraightToBrakeStateFrame: 5,
			Range_FreeGravity: 0.06,
			Range_BrakeAirResist: 0.1,
			Range_BrakeGravity: 0.04,
			Range_BrakeToFreeStateFrame: 1,
			MoveSpeed: 0.07,
			DamageParam_ValueDirectMax: 760,
			DamageParam_ValueDirectMin: 520,
			BlastParam_SplashDamage: 380,
			InkRecoverStop: 42,
			InkConsumeSlosher: 0.092,
		},
		"3030": {
			Range_SpawnSpeed: 0.53982,
			Range_GoStraightStateEndMaxSpeed: 10,
			Range_GoStraightToBrakeStateFrame: 3,
			Range_FreeGravity: 0.015,
			Range_BrakeAirResist: 0.01,
			Range_BrakeGravity: 0.01,
			Range_BrakeToFreeStateFrame: 1,
			Range_ZRate: 0.5,
			Range_BounceAfterMaxSpeed: 0.6,
			Range_BurstFrame: 3,
			MoveSpeed: 0.05,
			DamageParam_ValueDirect: 300,
			InkRecoverStop: 40,
			InkConsumeSlosher: 0.08,
		},
		"3040": {
			Range_SpawnSpeed: 1.4105,
			Range_GoStraightStateEndMaxSpeed: 10,
			Range_GoStraightToBrakeStateFrame: 8,
			Range_FreeGravity: 0.05,
			Range_BrakeAirResist: 0.1,
			Range_BrakeGravity: 0.04,
			Range_BrakeToFreeStateFrame: 1,
			Range_ZRate: 1,
			WeaponSpeedType: "Slow",
			MoveSpeed: 0.045,
			DamageParam_ValueDirect: 550,
			BlastParam_DistanceDamage: [
				{
					Damage: 350,
					Distance: 2.87,
				},
			],
			InkRecoverStop: 70,
			InkConsumeSlosher: 0.117,
		},
		"3050": {
			Range_SpawnSpeed: 1.85,
			Range_GoStraightStateEndMaxSpeed: 10,
			Range_GoStraightToBrakeStateFrame: 2,
			Range_FreeGravity: 0.05,
			Range_BrakeAirResist: 0.1,
			Range_BrakeGravity: 0.04,
			Range_BrakeToFreeStateFrame: 1,
			Range_ZRate: 2,
			MoveSpeed: 0.04,
			DamageParam_ValueDirectMax: 480,
			DamageParam_ValueDirectMin: 350,
			DamageParam_Secondary_ValueDirectMax: 420,
			DamageParam_Secondary_ValueDirectMin: 350,
			InkRecoverStop: 50,
			InkConsumeSlosher: 0.09,
		},
		"4000": {
			overwrites: {
				MoveVelRt_Shot: {
					High: 1.4,
					Low: 1,
					Mid: 1.2,
				},
			},
			Range_SpawnSpeed: 1.5,
			Range_GoStraightStateEndMaxSpeed: 1.105,
			Range_GoStraightToBrakeStateFrame: 8,
			MoveSpeed: 0.086,
			MoveSpeed_Charge: 0.072,
			DamageParam_ValueMax: 320,
			DamageParam_ValueMin: 160,
			Jump_DegSwerve: 8,
			Stand_DegSwerve: 4,
			InkRecoverStop: 30,
			InkConsumeFullChargeSplatling: 0.15,
		},
		"4010": {
			overwrites: {
				MoveVelRt_Shot: {
					High: 1.35,
					Low: 1,
					Mid: 1.175,
				},
			},
			Range_SpawnSpeed: 2.1,
			Range_GoStraightStateEndMaxSpeed: 1.5105,
			Range_GoStraightToBrakeStateFrame: 8,
			MoveSpeed: 0.07,
			MoveSpeed_Charge: 0.062,
			DamageParam_ValueMax: 300,
			DamageParam_ValueMin: 150,
			Jump_DegSwerve: 7,
			Stand_DegSwerve: 3.3,
			InkRecoverStop: 40,
			InkConsumeFullChargeSplatling: 0.225,
		},
		"4020": {
			overwrites: {
				ConsumeRt_Main: {
					High: 0.5,
					Low: 1,
					Mid: 0.7,
				},
				MoveVelRt_Shot: {
					High: 1.35,
					Low: 1,
					Mid: 1.175,
				},
			},
			Range_SpawnSpeed: 2.4,
			Range_GoStraightStateEndMaxSpeed: 1.94,
			Range_GoStraightToBrakeStateFrame: 8,
			WeaponSpeedType: "Slow",
			MoveSpeed: 0.06,
			MoveSpeed_Charge: 0.044,
			DamageParam_ValueMax: 320,
			DamageParam_ValueMin: 160,
			DamageParam_ValueFullChargeMax: 400,
			Jump_DegSwerve: 6,
			Stand_DegSwerve: 3,
			InkRecoverStop: 40,
			InkConsumeFullChargeSplatling: 0.35,
		},
		"4030": {
			overwrites: {
				MoveVelRt_Shot: {
					High: 1.25,
					Low: 1,
					Mid: 1.125,
				},
			},
			Range_SpawnSpeed: 2.21915,
			Range_GoStraightStateEndMaxSpeed: 10,
			Range_GoStraightToBrakeStateFrame: 8,
			MoveSpeed: 0.086,
			MoveSpeed_Charge: 0.086,
			MoveSpeedVariable: 0.05,
			DamageParam_ValueMax: 280,
			DamageParam_ValueMin: 140,
			Variable_Damage_ValueMax: 300,
			Variable_Damage_ValueMin: 150,
			Jump_DegSwerve: 12,
			Stand_DegSwerve: 6,
			Variable_Jump_DegSwerve: 4,
			Variable_Stand_DegSwerve: 1.5,
			InkRecoverStop: 40,
			InkConsumeFullChargeSplatling: 0.25,
		},
		"4040": {
			overwrites: {
				MoveVelRt_Shot: {
					High: 1.3,
					Low: 1,
					Mid: 1.15,
				},
			},
			Range_SpawnSpeed: 4.4333,
			Range_GoStraightStateEndMaxSpeed: 1.8215,
			Range_GoStraightToBrakeStateFrame: 3,
			MoveSpeed: 0.07,
			MoveSpeed_Charge: 0.04,
			DamageParam_ValueMax: 320,
			DamageParam_ValueMin: 160,
			KeepChargeFullFrame: 200,
			Jump_DegSwerve: 3.6,
			Stand_DegSwerve: 3.3,
			InkRecoverStop: 40,
			InkConsumeFullChargeSplatling: 0.15,
		},
		"4050": {
			overwrites: {
				MoveVelRt_Shot: {
					High: 1.4,
					Low: 1,
					Mid: 1.2,
				},
			},
			Range_SpawnSpeed: 1.8,
			Range_GoStraightStateEndMaxSpeed: 1.105,
			Range_GoStraightToBrakeStateFrame: 8,
			MoveSpeed: 0.086,
			MoveSpeed_Charge: 0.072,
			DamageParam_ValueMax: 260,
			DamageParam_ValueMin: 130,
			Jump_DegSwerve: 6,
			Stand_DegSwerve: 3,
			InkRecoverStop: 40,
			InkConsumeFullChargeSplatling: 0.2,
		},
		"5000": {
			Range_SpawnSpeed: 1.8334,
			Range_GoStraightStateEndMaxSpeed: 1.81641,
			Range_GoStraightToBrakeStateFrame: 3,
			Range_FreeGravity: 0.016,
			Range_ZRate: 2,
			WeaponSpeedType: "Fast",
			MoveSpeed: 0.084,
			DamageParam_ValueMax: 360,
			DamageParam_ValueMin: 180,
			Jump_DegSwerve: 11.66,
			Stand_DegSwerve: 6.8,
			InkConsume: 0.00663,
			InkConsume_SideStepParam: 0.05,
		},
		"5010": {
			Range_SpawnSpeed: 2.37,
			Range_GoStraightStateEndMaxSpeed: 2.3425,
			Range_GoStraightToBrakeStateFrame: 3,
			Range_FreeGravity: 0.016,
			Range_ZRate: 2,
			MoveSpeed: 0.08,
			DamageParam_ValueMax: 300,
			DamageParam_ValueMin: 150,
			Jump_DegSwerve: 7.5,
			Stand_DegSwerve: 2,
			InkConsume: 0.0072,
			InkConsume_SideStepParam: 0.07,
		},
		"5020": {
			Range_SpawnSpeed: 2.85,
			Range_GoStraightStateEndMaxSpeed: 2.8115,
			Range_GoStraightToBrakeStateFrame: 3,
			Range_FreeGravity: 0.016,
			Range_ZRate: 2,
			MoveSpeed: 0.06,
			DamageParam_ValueMax: 360,
			DamageParam_ValueMin: 180,
			DamageLapOverParam_ValueMax: 525,
			DamageLapOverParam_ValueMin: 263,
			Jump_DegSwerve: 8,
			Stand_DegSwerve: 3.2,
			InkConsume: 0.014,
			InkConsume_SideStepParam: 0.08,
		},
		"5030": {
			Range_SpawnSpeed: 2.3,
			Range_GoStraightStateEndMaxSpeed: 2.2698,
			Range_GoStraightToBrakeStateFrame: 5,
			Range_FreeGravity: 0.016,
			Range_ZRate: 2,
			MoveSpeed: 0.072,
			DamageParam_ValueMax: 280,
			DamageParam_ValueMin: 140,
			Jump_DegSwerve: 8,
			Stand_DegSwerve: 4,
			InkConsume: 0.012,
			InkConsume_SideStepParam: 0.08,
		},
		"5040": {
			Range_SpawnSpeed: 2.637,
			Range_GoStraightStateEndMaxSpeed: 2.631,
			Range_GoStraightToBrakeStateFrame: 3,
			Range_FreeGravity: 0.016,
			Range_ZRate: 2,
			MoveSpeed: 0.072,
			DamageParam_ValueMax: 280,
			DamageParam_ValueMin: 140,
			Jump_DegSwerve: 12.8,
			Stand_DegSwerve: 7.4,
			InkConsume: 0.008,
			InkConsume_SideStepParam: 0.03,
		},
		"5050": {
			Range_SpawnSpeed: 3.72,
			Range_GoStraightStateEndMaxSpeed: 2.325,
			Range_GoStraightToBrakeStateFrame: 4,
			Range_FreeGravity: 0.016,
			Range_ZRate: 2,
			MoveSpeed: 0.07,
			DamageParam_ValueMax: 255,
			DamageParam_ValueMin: 128,
			DamageLapOverParam_ValueMax: 255,
			DamageLapOverParam_ValueMin: 128,
			Jump_DegSwerve: 8,
			Stand_DegSwerve: 2.5,
			InkConsume: 0.012,
			InkConsume_SideStepParam: 0.1,
		},
		"6000": {
			Range_SpawnSpeed: 2.6,
			Range_GoStraightStateEndMaxSpeed: 1.652,
			Range_GoStraightToBrakeStateFrame: 3,
			Range_ZRate: 2,
			MoveSpeed: 0.065,
			DamageParam_ValueMax: 810,
			CanopyHP: 5000,
			InkConsumeUmbrella_WeaponShelterCanopyParam: 0.3,
			InkConsume_WeaponShelterShotgunParam: 0.05,
		},
		"6010": {
			overwrites: {
				ConsumeRt_Main: {
					High: 0.5,
					Mid: 0.7,
				},
			},
			Range_SpawnSpeed: 2.4,
			Range_GoStraightStateEndMaxSpeed: 2.3135,
			Range_GoStraightToBrakeStateFrame: 4,
			Range_ZRate: 2,
			WeaponSpeedType: "Slow",
			MoveSpeed: 0.05,
			DamageParam_ValueMax: 1190,
			CanopyHP: 7000,
			InkConsumeUmbrella_WeaponShelterCanopyParam: 0.3,
			InkConsume_WeaponShelterShotgunParam: 0.11,
		},
		"6020": {
			Range_SpawnSpeed: 2,
			Range_GoStraightStateEndMaxSpeed: 1.9085,
			Range_GoStraightToBrakeStateFrame: 4,
			Range_ZRate: 2,
			WeaponSpeedType: "Fast",
			MoveSpeed: 0.072,
			DamageParam_ValueMax: 400,
			CanopyHP: 2000,
			InkConsume_WeaponShelterShotgunParam: 0.04,
		},
		"6030": {
			Range_SpawnSpeed: 3,
			Range_GoStraightStateEndMaxSpeed: 2,
			Range_GoStraightToBrakeStateFrame: 3,
			Range_ZRate: 2,
			MoveSpeed: 0.058,
			DamageParam_ValueMax: 900,
			CanopyHP: 1500,
			InkConsumeUmbrella_WeaponShelterCanopyParam: 0.15,
			InkConsume_WeaponShelterShotgunParam: 0.06,
		},
		"7010": {
			Range_SpawnSpeed: 3.85,
			Range_GoStraightStateEndMaxSpeed: 10,
			Range_GoStraightToBrakeStateFrame: 4,
			Range_FreeGravity: 0.15,
			Range_BrakeAirResist: 0.1,
			Range_BrakeGravity: 0.04,
			Range_BrakeToFreeStateFrame: 1,
			BlastRadius: 2.05,
			MoveSpeedFullCharge: 0.068,
			DamageParam_ValueMax: 350,
			DamageParam_ValueMin: 300,
			BlastParam_DistanceDamage: [
				{
					Damage: 300,
					Distance: 2.05,
				},
			],
			ChargeFrameFullCharge: 72,
			InkConsumeFullCharge_ChargeParam: 0.085,
		},
		"7020": {
			Range_SpawnSpeed: 2.55,
			Range_GoStraightStateEndMaxSpeed: 10,
			Range_GoStraightToBrakeStateFrame: 4,
			Range_FreeGravity: 0.15,
			Range_BrakeAirResist: 0.1,
			Range_BrakeGravity: 0.04,
			Range_BrakeToFreeStateFrame: 1,
			WeaponSpeedType: "Fast",
			MoveSpeedFullCharge: 0.084,
			DamageParam_ValueMax: 450,
			DamageParam_ValueMin: 300,
			ChargeFrameFullCharge: 34,
			KeepChargeFullFrame: 75,
			InkConsumeFullCharge_ChargeParam: 0.065,
		},
		"7030": {
			Range_SpawnSpeed: 3.5,
			Range_GoStraightStateEndMaxSpeed: 10,
			Range_GoStraightToBrakeStateFrame: 4,
			Range_FreeGravity: 0.15,
			Range_BrakeAirResist: 0.1,
			Range_BrakeGravity: 0.04,
			Range_BrakeToFreeStateFrame: 1,
			BlastRadius: 2.05,
			WeaponSpeedType: "Slow",
			MoveSpeedFullCharge: 0.04,
			DamageParam_ValueMax: 350,
			DamageParam_ValueMin: 240,
			BlastParam_DistanceDamage: [
				{
					Damage: 300,
					Distance: 2.05,
				},
			],
			ChargeFrameFullCharge: 80,
			InkConsumeFullCharge_ChargeParam: 0.09,
		},
		"8000": {
			Range_SpawnSpeed: 0.8,
			Range_GoStraightStateEndMaxSpeed: 10,
			Range_GoStraightToBrakeStateFrame: 22,
			Range_FreeGravity: 0.02,
			Range_BrakeAirResist: 0,
			Range_BrakeGravity: 0.0027,
			Range_BrakeToFreeStateFrame: 0,
			Range_BurstFrame: 26,
			DamageParam_SplatanaVerticalDirect: 1400,
			DamageParam_SplatanaVertical: 700,
			DamageParam_SplatanaHorizontalDirect: 550,
			DamageParam_SplatanaHorizontal: 350,
			InkConsume_SwingParam: 0.052,
			InkConsumeFullCharge_ChargeParam: 0.117,
		},
		"8010": {
			Range_SpawnSpeed: 1.2,
			Range_GoStraightStateEndMaxSpeed: 10,
			Range_GoStraightToBrakeStateFrame: 10,
			Range_FreeGravity: 0.1,
			Range_BrakeAirResist: 0,
			Range_BrakeGravity: 0.02,
			Range_BrakeToFreeStateFrame: 0,
			Range_BurstFrame: 14,
			WeaponSpeedType: "Fast",
			DamageParam_SplatanaVerticalDirect: 1200,
			DamageParam_SplatanaVertical: 600,
			DamageParam_SplatanaHorizontalDirect: 450,
			DamageParam_SplatanaHorizontal: 300,
			InkConsume_SwingParam: 0.03,
			InkConsumeFullCharge_ChargeParam: 0.06,
		},
		"8020": {
			Range_SpawnSpeed: 0.7,
			Range_GoStraightStateEndMaxSpeed: 10,
			Range_GoStraightToBrakeStateFrame: 21,
			Range_FreeGravity: 0.1,
			Range_BrakeAirResist: 0,
			Range_BrakeGravity: 0.02,
			Range_BrakeToFreeStateFrame: 0,
			Range_BurstFrame: 21,
			DamageParam_SplatanaVerticalDirect: 1600,
			DamageParam_SplatanaVertical: 800,
			DamageParam_SplatanaHorizontalDirect: 700,
			DamageParam_SplatanaHorizontal: 400,
			InkConsume_SwingParam: 0.065,
			InkConsumeFullCharge_ChargeParam: 0.13,
		},
	},
	weaponKits: {
		"0": {
			SpecialPoint: 180,
			subWeaponId: 6,
			specialWeaponId: 11,
		},
		"1": {
			SpecialPoint: 170,
			subWeaponId: 8,
			specialWeaponId: 9,
		},
		"10": {
			SpecialPoint: 180,
			subWeaponId: 0,
			specialWeaponId: 2,
		},
		"11": {
			SpecialPoint: 190,
			subWeaponId: 13,
			specialWeaponId: 7,
		},
		"20": {
			SpecialPoint: 200,
			subWeaponId: 2,
			specialWeaponId: 12,
		},
		"21": {
			SpecialPoint: 200,
			subWeaponId: 1,
			specialWeaponId: 14,
		},
		"22": {
			SpecialPoint: 180,
			subWeaponId: 11,
			specialWeaponId: 5,
		},
		"30": {
			SpecialPoint: 180,
			subWeaponId: 5,
			specialWeaponId: 13,
		},
		"31": {
			SpecialPoint: 190,
			subWeaponId: 3,
			specialWeaponId: 6,
		},
		"32": {
			SpecialPoint: 180,
			subWeaponId: 2,
			specialWeaponId: 19,
		},
		"40": {
			SpecialPoint: 210,
			subWeaponId: 1,
			specialWeaponId: 1,
		},
		"41": {
			SpecialPoint: 190,
			subWeaponId: 0,
			specialWeaponId: 14,
		},
		"42": {
			SpecialPoint: 190,
			subWeaponId: 2,
			specialWeaponId: 17,
		},
		"45": {
			SpecialPoint: 210,
			subWeaponId: 1,
			specialWeaponId: 1,
		},
		"46": {
			SpecialPoint: 190,
			subWeaponId: 0,
			specialWeaponId: 14,
		},
		"47": {
			SpecialPoint: 210,
			subWeaponId: 1,
			specialWeaponId: 1,
		},
		"50": {
			SpecialPoint: 200,
			subWeaponId: 4,
			specialWeaponId: 9,
		},
		"51": {
			SpecialPoint: 190,
			subWeaponId: 6,
			specialWeaponId: 19,
		},
		"60": {
			SpecialPoint: 200,
			subWeaponId: 1,
			specialWeaponId: 15,
		},
		"61": {
			SpecialPoint: 170,
			subWeaponId: 7,
			specialWeaponId: 16,
		},
		"70": {
			SpecialPoint: 190,
			subWeaponId: 12,
			specialWeaponId: 12,
		},
		"71": {
			SpecialPoint: 200,
			subWeaponId: 1,
			specialWeaponId: 6,
		},
		"72": {
			SpecialPoint: 190,
			subWeaponId: 0,
			specialWeaponId: 4,
		},
		"80": {
			SpecialPoint: 190,
			subWeaponId: 3,
			specialWeaponId: 8,
		},
		"81": {
			SpecialPoint: 210,
			subWeaponId: 4,
			specialWeaponId: 17,
		},
		"82": {
			SpecialPoint: 190,
			subWeaponId: 12,
			specialWeaponId: 15,
		},
		"90": {
			SpecialPoint: 180,
			subWeaponId: 12,
			specialWeaponId: 8,
		},
		"91": {
			SpecialPoint: 180,
			subWeaponId: 11,
			specialWeaponId: 5,
		},
		"92": {
			SpecialPoint: 190,
			subWeaponId: 2,
			specialWeaponId: 18,
		},
		"100": {
			SpecialPoint: 190,
			subWeaponId: 9,
			specialWeaponId: 9,
		},
		"101": {
			SpecialPoint: 210,
			subWeaponId: 10,
			specialWeaponId: 10,
		},
		"200": {
			SpecialPoint: 170,
			subWeaponId: 0,
			specialWeaponId: 3,
		},
		"201": {
			SpecialPoint: 180,
			subWeaponId: 5,
			specialWeaponId: 11,
		},
		"205": {
			SpecialPoint: 170,
			subWeaponId: 0,
			specialWeaponId: 3,
		},
		"210": {
			SpecialPoint: 180,
			subWeaponId: 7,
			specialWeaponId: 2,
		},
		"211": {
			SpecialPoint: 180,
			subWeaponId: 9,
			specialWeaponId: 18,
		},
		"212": {
			SpecialPoint: 180,
			subWeaponId: 8,
			specialWeaponId: 12,
		},
		"220": {
			SpecialPoint: 210,
			subWeaponId: 1,
			specialWeaponId: 7,
		},
		"221": {
			SpecialPoint: 210,
			subWeaponId: 0,
			specialWeaponId: 17,
		},
		"230": {
			SpecialPoint: 180,
			subWeaponId: 0,
			specialWeaponId: 1,
		},
		"231": {
			SpecialPoint: 170,
			subWeaponId: 6,
			specialWeaponId: 16,
		},
		"240": {
			SpecialPoint: 190,
			subWeaponId: 10,
			specialWeaponId: 14,
		},
		"241": {
			SpecialPoint: 210,
			subWeaponId: 13,
			specialWeaponId: 10,
		},
		"250": {
			SpecialPoint: 180,
			subWeaponId: 11,
			specialWeaponId: 8,
		},
		"251": {
			SpecialPoint: 190,
			subWeaponId: 12,
			specialWeaponId: 9,
		},
		"252": {
			SpecialPoint: 200,
			subWeaponId: 1,
			specialWeaponId: 15,
		},
		"260": {
			SpecialPoint: 180,
			subWeaponId: 3,
			specialWeaponId: 13,
		},
		"261": {
			SpecialPoint: 210,
			subWeaponId: 2,
			specialWeaponId: 6,
		},
		"300": {
			SpecialPoint: 190,
			subWeaponId: 6,
			specialWeaponId: 12,
		},
		"301": {
			SpecialPoint: 200,
			subWeaponId: 2,
			specialWeaponId: 11,
		},
		"302": {
			SpecialPoint: 200,
			subWeaponId: 0,
			specialWeaponId: 10,
		},
		"310": {
			SpecialPoint: 190,
			subWeaponId: 9,
			specialWeaponId: 15,
		},
		"311": {
			SpecialPoint: 200,
			subWeaponId: 4,
			specialWeaponId: 2,
		},
		"312": {
			SpecialPoint: 200,
			subWeaponId: 1,
			specialWeaponId: 14,
		},
		"400": {
			SpecialPoint: 220,
			subWeaponId: 4,
			specialWeaponId: 1,
		},
		"401": {
			SpecialPoint: 190,
			subWeaponId: 7,
			specialWeaponId: 19,
		},
		"1000": {
			SpecialPoint: 160,
			subWeaponId: 7,
			specialWeaponId: 3,
		},
		"1001": {
			SpecialPoint: 190,
			subWeaponId: 2,
			specialWeaponId: 1,
		},
		"1002": {
			SpecialPoint: 170,
			subWeaponId: 5,
			specialWeaponId: 16,
		},
		"1010": {
			SpecialPoint: 180,
			subWeaponId: 6,
			specialWeaponId: 2,
		},
		"1011": {
			SpecialPoint: 170,
			subWeaponId: 8,
			specialWeaponId: 17,
		},
		"1015": {
			SpecialPoint: 180,
			subWeaponId: 6,
			specialWeaponId: 2,
		},
		"1020": {
			SpecialPoint: 190,
			subWeaponId: 3,
			specialWeaponId: 15,
		},
		"1021": {
			SpecialPoint: 180,
			subWeaponId: 0,
			specialWeaponId: 16,
		},
		"1022": {
			SpecialPoint: 180,
			subWeaponId: 9,
			specialWeaponId: 9,
		},
		"1030": {
			SpecialPoint: 210,
			subWeaponId: 10,
			specialWeaponId: 4,
		},
		"1031": {
			SpecialPoint: 200,
			subWeaponId: 1,
			specialWeaponId: 19,
		},
		"1040": {
			SpecialPoint: 180,
			subWeaponId: 4,
			specialWeaponId: 8,
		},
		"1041": {
			SpecialPoint: 180,
			subWeaponId: 12,
			specialWeaponId: 5,
		},
		"1042": {
			SpecialPoint: 180,
			subWeaponId: 13,
			specialWeaponId: 18,
		},
		"1100": {
			SpecialPoint: 180,
			subWeaponId: 0,
			specialWeaponId: 9,
		},
		"1101": {
			SpecialPoint: 180,
			subWeaponId: 10,
			specialWeaponId: 11,
		},
		"1110": {
			SpecialPoint: 190,
			subWeaponId: 1,
			specialWeaponId: 3,
		},
		"1111": {
			SpecialPoint: 180,
			subWeaponId: 8,
			specialWeaponId: 5,
		},
		"1112": {
			SpecialPoint: 190,
			subWeaponId: 7,
			specialWeaponId: 17,
		},
		"1115": {
			SpecialPoint: 190,
			subWeaponId: 1,
			specialWeaponId: 3,
		},
		"1120": {
			SpecialPoint: 190,
			subWeaponId: 6,
			specialWeaponId: 7,
		},
		"1121": {
			SpecialPoint: 190,
			subWeaponId: 9,
			specialWeaponId: 4,
		},
		"1122": {
			SpecialPoint: 190,
			subWeaponId: 4,
			specialWeaponId: 1,
		},
		"2000": {
			SpecialPoint: 190,
			subWeaponId: 9,
			specialWeaponId: 2,
		},
		"2001": {
			SpecialPoint: 190,
			subWeaponId: 7,
			specialWeaponId: 3,
		},
		"2010": {
			SpecialPoint: 190,
			subWeaponId: 0,
			specialWeaponId: 8,
		},
		"2011": {
			SpecialPoint: 200,
			subWeaponId: 4,
			specialWeaponId: 14,
		},
		"2012": {
			SpecialPoint: 200,
			subWeaponId: 3,
			specialWeaponId: 12,
		},
		"2015": {
			SpecialPoint: 190,
			subWeaponId: 0,
			specialWeaponId: 8,
		},
		"2020": {
			SpecialPoint: 190,
			subWeaponId: 0,
			specialWeaponId: 8,
		},
		"2021": {
			SpecialPoint: 200,
			subWeaponId: 4,
			specialWeaponId: 14,
		},
		"2022": {
			SpecialPoint: 200,
			subWeaponId: 3,
			specialWeaponId: 12,
		},
		"2030": {
			SpecialPoint: 210,
			subWeaponId: 10,
			specialWeaponId: 7,
		},
		"2031": {
			SpecialPoint: 210,
			subWeaponId: 8,
			specialWeaponId: 17,
		},
		"2040": {
			SpecialPoint: 210,
			subWeaponId: 10,
			specialWeaponId: 7,
		},
		"2041": {
			SpecialPoint: 210,
			subWeaponId: 8,
			specialWeaponId: 17,
		},
		"2050": {
			SpecialPoint: 190,
			subWeaponId: 7,
			specialWeaponId: 9,
		},
		"2051": {
			SpecialPoint: 190,
			subWeaponId: 5,
			specialWeaponId: 16,
		},
		"2060": {
			SpecialPoint: 200,
			subWeaponId: 13,
			specialWeaponId: 4,
		},
		"2061": {
			SpecialPoint: 200,
			subWeaponId: 5,
			specialWeaponId: 11,
		},
		"2070": {
			SpecialPoint: 220,
			subWeaponId: 3,
			specialWeaponId: 15,
		},
		"2071": {
			SpecialPoint: 210,
			subWeaponId: 4,
			specialWeaponId: 5,
		},
		"3000": {
			SpecialPoint: 210,
			subWeaponId: 0,
			specialWeaponId: 14,
		},
		"3001": {
			SpecialPoint: 180,
			subWeaponId: 12,
			specialWeaponId: 3,
		},
		"3005": {
			SpecialPoint: 210,
			subWeaponId: 0,
			specialWeaponId: 14,
		},
		"3010": {
			SpecialPoint: 180,
			subWeaponId: 11,
			specialWeaponId: 10,
		},
		"3011": {
			SpecialPoint: 200,
			subWeaponId: 5,
			specialWeaponId: 15,
		},
		"3012": {
			SpecialPoint: 180,
			subWeaponId: 0,
			specialWeaponId: 19,
		},
		"3020": {
			SpecialPoint: 210,
			subWeaponId: 5,
			specialWeaponId: 6,
		},
		"3021": {
			SpecialPoint: 190,
			subWeaponId: 9,
			specialWeaponId: 1,
		},
		"3030": {
			SpecialPoint: 190,
			subWeaponId: 3,
			specialWeaponId: 5,
		},
		"3031": {
			SpecialPoint: 190,
			subWeaponId: 12,
			specialWeaponId: 17,
		},
		"3040": {
			SpecialPoint: 200,
			subWeaponId: 9,
			specialWeaponId: 5,
		},
		"3041": {
			SpecialPoint: 190,
			subWeaponId: 4,
			specialWeaponId: 18,
		},
		"3050": {
			SpecialPoint: 190,
			subWeaponId: 1,
			specialWeaponId: 13,
		},
		"3051": {
			SpecialPoint: 190,
			subWeaponId: 8,
			specialWeaponId: 7,
		},
		"3052": {
			SpecialPoint: 200,
			subWeaponId: 6,
			specialWeaponId: 12,
		},
		"4000": {
			SpecialPoint: 200,
			subWeaponId: 2,
			specialWeaponId: 11,
		},
		"4001": {
			SpecialPoint: 200,
			subWeaponId: 11,
			specialWeaponId: 2,
		},
		"4002": {
			SpecialPoint: 200,
			subWeaponId: 8,
			specialWeaponId: 1,
		},
		"4010": {
			SpecialPoint: 200,
			subWeaponId: 3,
			specialWeaponId: 7,
		},
		"4011": {
			SpecialPoint: 200,
			subWeaponId: 9,
			specialWeaponId: 17,
		},
		"4015": {
			SpecialPoint: 200,
			subWeaponId: 3,
			specialWeaponId: 7,
		},
		"4020": {
			SpecialPoint: 190,
			subWeaponId: 7,
			specialWeaponId: 6,
		},
		"4021": {
			SpecialPoint: 200,
			subWeaponId: 10,
			specialWeaponId: 19,
		},
		"4022": {
			SpecialPoint: 200,
			subWeaponId: 3,
			specialWeaponId: 2,
		},
		"4030": {
			SpecialPoint: 210,
			subWeaponId: 5,
			specialWeaponId: 10,
		},
		"4031": {
			SpecialPoint: 200,
			subWeaponId: 10,
			specialWeaponId: 8,
		},
		"4040": {
			SpecialPoint: 190,
			subWeaponId: 9,
			specialWeaponId: 5,
		},
		"4041": {
			SpecialPoint: 200,
			subWeaponId: 1,
			specialWeaponId: 18,
		},
		"4050": {
			SpecialPoint: 200,
			subWeaponId: 6,
			specialWeaponId: 15,
		},
		"4051": {
			SpecialPoint: 210,
			subWeaponId: 0,
			specialWeaponId: 12,
		},
		"5000": {
			SpecialPoint: 170,
			subWeaponId: 8,
			specialWeaponId: 15,
		},
		"5001": {
			SpecialPoint: 190,
			subWeaponId: 13,
			specialWeaponId: 13,
		},
		"5002": {
			SpecialPoint: 190,
			subWeaponId: 0,
			specialWeaponId: 9,
		},
		"5010": {
			SpecialPoint: 190,
			subWeaponId: 1,
			specialWeaponId: 12,
		},
		"5011": {
			SpecialPoint: 190,
			subWeaponId: 6,
			specialWeaponId: 18,
		},
		"5012": {
			SpecialPoint: 190,
			subWeaponId: 5,
			specialWeaponId: 2,
		},
		"5015": {
			SpecialPoint: 190,
			subWeaponId: 1,
			specialWeaponId: 12,
		},
		"5020": {
			SpecialPoint: 180,
			subWeaponId: 4,
			specialWeaponId: 6,
		},
		"5021": {
			SpecialPoint: 190,
			subWeaponId: 9,
			specialWeaponId: 1,
		},
		"5030": {
			SpecialPoint: 200,
			subWeaponId: 0,
			specialWeaponId: 7,
		},
		"5031": {
			SpecialPoint: 200,
			subWeaponId: 8,
			specialWeaponId: 16,
		},
		"5032": {
			SpecialPoint: 190,
			subWeaponId: 9,
			specialWeaponId: 19,
		},
		"5040": {
			SpecialPoint: 200,
			subWeaponId: 7,
			specialWeaponId: 13,
		},
		"5041": {
			SpecialPoint: 190,
			subWeaponId: 3,
			specialWeaponId: 3,
		},
		"5050": {
			SpecialPoint: 190,
			subWeaponId: 10,
			specialWeaponId: 9,
		},
		"5051": {
			SpecialPoint: 200,
			subWeaponId: 2,
			specialWeaponId: 14,
		},
		"6000": {
			SpecialPoint: 210,
			subWeaponId: 3,
			specialWeaponId: 14,
		},
		"6001": {
			SpecialPoint: 210,
			subWeaponId: 7,
			specialWeaponId: 10,
		},
		"6005": {
			SpecialPoint: 210,
			subWeaponId: 3,
			specialWeaponId: 14,
		},
		"6010": {
			SpecialPoint: 190,
			subWeaponId: 8,
			specialWeaponId: 8,
		},
		"6011": {
			SpecialPoint: 200,
			subWeaponId: 10,
			specialWeaponId: 1,
		},
		"6012": {
			SpecialPoint: 180,
			subWeaponId: 11,
			specialWeaponId: 16,
		},
		"6020": {
			SpecialPoint: 180,
			subWeaponId: 10,
			specialWeaponId: 13,
		},
		"6021": {
			SpecialPoint: 180,
			subWeaponId: 13,
			specialWeaponId: 19,
		},
		"6022": {
			SpecialPoint: 180,
			subWeaponId: 6,
			specialWeaponId: 9,
		},
		"6030": {
			SpecialPoint: 190,
			subWeaponId: 12,
			specialWeaponId: 2,
		},
		"6031": {
			SpecialPoint: 190,
			subWeaponId: 11,
			specialWeaponId: 18,
		},
		"7010": {
			SpecialPoint: 190,
			subWeaponId: 11,
			specialWeaponId: 9,
		},
		"7011": {
			SpecialPoint: 190,
			subWeaponId: 3,
			specialWeaponId: 16,
		},
		"7012": {
			SpecialPoint: 200,
			subWeaponId: 12,
			specialWeaponId: 10,
		},
		"7015": {
			SpecialPoint: 190,
			subWeaponId: 11,
			specialWeaponId: 9,
		},
		"7020": {
			SpecialPoint: 210,
			subWeaponId: 6,
			specialWeaponId: 4,
		},
		"7021": {
			SpecialPoint: 200,
			subWeaponId: 4,
			specialWeaponId: 13,
		},
		"7022": {
			SpecialPoint: 210,
			subWeaponId: 13,
			specialWeaponId: 6,
		},
		"7030": {
			SpecialPoint: 200,
			subWeaponId: 7,
			specialWeaponId: 11,
		},
		"7031": {
			SpecialPoint: 200,
			subWeaponId: 9,
			specialWeaponId: 7,
		},
		"8000": {
			SpecialPoint: 210,
			subWeaponId: 2,
			specialWeaponId: 3,
		},
		"8001": {
			SpecialPoint: 210,
			subWeaponId: 11,
			specialWeaponId: 12,
		},
		"8002": {
			SpecialPoint: 190,
			subWeaponId: 7,
			specialWeaponId: 6,
		},
		"8005": {
			SpecialPoint: 210,
			subWeaponId: 2,
			specialWeaponId: 3,
		},
		"8010": {
			SpecialPoint: 190,
			subWeaponId: 13,
			specialWeaponId: 11,
		},
		"8011": {
			SpecialPoint: 190,
			subWeaponId: 8,
			specialWeaponId: 4,
		},
		"8012": {
			SpecialPoint: 190,
			subWeaponId: 6,
			specialWeaponId: 1,
		},
		"8020": {
			SpecialPoint: 210,
			subWeaponId: 1,
			specialWeaponId: 2,
		},
		"8021": {
			SpecialPoint: 200,
			subWeaponId: 4,
			specialWeaponId: 10,
		},
	},
	subWeapons: {
		"0": {
			overwrites: {
				SpawnSpeedZSpecUp: {
					High: 1.68,
					Low: 1.12,
					Mid: 1.4,
				},
			},
			SubInkSaveLv: 2,
			InkConsume: 0.7,
			InkRecoverStop: 60,
			DistanceDamage: [
				{
					Damage: 1800,
					Distance: 3.6,
				},
				{
					Damage: 300,
					Distance: 7,
				},
			],
		},
		"1": {
			overwrites: {
				SpawnSpeedZSpecUp: {
					High: 1.68,
					Low: 1.12,
					Mid: 1.4,
				},
			},
			SubInkSaveLv: 2,
			InkConsume: 0.7,
			InkRecoverStop: 60,
			DistanceDamage: [
				{
					Damage: 1800,
					Distance: 4.6,
				},
				{
					Damage: 300,
					Distance: 8,
				},
			],
		},
		"2": {
			overwrites: {
				SpawnSpeedZSpecUp: {
					High: 1.68,
					Low: 1.12,
					Mid: 1.4,
				},
			},
			SubInkSaveLv: 4,
			InkConsume: 0.45,
			InkRecoverStop: 60,
			DistanceDamage: [
				{
					Damage: 350,
					Distance: 2.8,
				},
				{
					Damage: 250,
					Distance: 4,
				},
			],
		},
		"3": {
			overwrites: {
				PeriodFirst: {
					High: 780,
					Low: 480,
					Mid: 630,
				},
				PeriodSecond: {
					High: 1020,
					Low: 900,
					Mid: 960,
				},
			},
			SubInkSaveLv: 3,
			InkConsume: 0.6,
			InkRecoverStop: 60,
		},
		"4": {
			overwrites: {
				MaxHP: {
					High: 15000,
					Low: 8000,
					Mid: 11500,
				},
			},
			SubInkSaveLv: 2,
			InkConsume: 0.6,
			InkRecoverStop: 85,
		},
		"5": {
			overwrites: {
				SpawnSpeedZSpecUp: {
					High: 1.84,
					Low: 1.36,
					Mid: 1.6,
				},
			},
			SubInkSaveLv: 1,
			InkConsume: 0.6,
			InkRecoverStop: 85,
			DistanceDamage_BlastParamArray: [
				[
					{
						Damage: 500,
						Distance: 1.6,
					},
					{
						Damage: 350,
						Distance: 3.8,
					},
				],
				[
					{
						Damage: 500,
						Distance: 1.95,
					},
					{
						Damage: 350,
						Distance: 4.5,
					},
				],
				[
					{
						Damage: 500,
						Distance: 2.6,
					},
					{
						Damage: 350,
						Distance: 5.45,
					},
				],
			],
		},
		"6": {
			overwrites: {
				SpawnSpeedZSpecUp: {
					High: 0.52,
					Low: 0.4,
					Mid: 0.46,
				},
			},
			SubInkSaveLv: 2,
			InkConsume: 0.65,
			InkRecoverStop: 70,
			DistanceDamage: [
				[
					{
						Damage: 1800,
						Distance: 4.6,
					},
					{
						Damage: 300,
						Distance: 8,
					},
				],
				[
					{
						Damage: 1800,
						Distance: 1.6,
					},
					{
						Damage: 300,
						Distance: 5,
					},
				],
			],
			DirectDamage: 200,
		},
		"7": {
			overwrites: {
				SpawnSpeedZSpecUp: {
					High: 1.68,
					Low: 1.12,
					Mid: 1.4,
				},
			},
			SubInkSaveLv: 1,
			InkConsume: 0.55,
			InkRecoverStop: 85,
			DistanceDamage: [
				{
					Damage: 1800,
					Distance: 2.85,
				},
				{
					Damage: 300,
					Distance: 6.5,
				},
			],
		},
		"8": {
			overwrites: {
				SubSpecUpParam: {
					Low: 0,
					High: 57,
					Mid: 25,
				},
			},
			SubInkSaveLv: 3,
			InkConsume: 0.75,
			InkRecoverStop: 0,
		},
		"9": {
			overwrites: {
				SpawnSpeedZSpecUp: {
					High: 1.87,
					Low: 1.38,
					Mid: 1.64,
				},
				MarkingFrameSubSpec: {
					High: 960,
					Low: 480,
					Mid: 720,
				},
			},
			SubInkSaveLv: 1,
			InkConsume: 0.45,
			InkRecoverStop: 75,
		},
		"10": {
			overwrites: {
				MarkingFrameSubSpec: {
					High: 600,
					Low: 300,
					Mid: 450,
				},
				SensorRadius: {
					High: 4,
					Low: 3,
					Mid: 3.5,
				},
				ExplosionRadius: {
					High: 11,
					Low: 8,
					Mid: 9.5,
				},
			},
			SubInkSaveLv: 3,
			InkConsume: 0.6,
			InkRecoverStop: 0,
			DistanceDamage: [
				{
					Damage: 450,
					Distance: 3.6,
				},
				{
					Damage: 350,
					Distance: 8,
				},
			],
		},
		"11": {
			overwrites: {
				SpawnSpeedZSpecUp: {
					High: 1.68,
					Low: 1.12,
					Mid: 1.4,
				},
			},
			SubInkSaveLv: 1,
			InkConsume: 0.55,
			InkRecoverStop: 80,
		},
		"12": {
			overwrites: {
				SpawnSpeedZSpecUp: {
					High: 6.8,
					Low: 6.3,
					Mid: 6.55,
				},
				MarkingFrameSubSpec: {
					High: 600,
					Low: 300,
					Mid: 450,
				},
			},
			SubInkSaveLv: 0,
			InkConsume: 0.4,
			InkRecoverStop: 50,
			DirectDamage: 400,
		},
		"13": {
			overwrites: {
				SpawnSpeedZSpecUp: {
					High: 1.9,
					Low: 1.4,
					Mid: 1.65,
				},
			},
			SubInkSaveLv: 2,
			InkConsume: 0.65,
			InkRecoverStop: 88,
			DistanceDamage_BlastParamChase: [
				{
					Damage: 600,
					Distance: 2.6,
				},
				{
					Damage: 350,
					Distance: 6,
				},
			],
			DistanceDamage_SplashBlastParam: [
				{
					Damage: 120,
					Distance: 2.6,
				},
			],
		},
	},
	specialWeapons: {
		"1": {
			overwrites: {
				PaintRadius: {
					High: 4,
					Low: 3.2,
					Mid: 3.6,
				},
				DistanceDamageDistanceRate: {
					High: 1.3,
					Low: 1,
					Mid: 1.15,
				},
				SpecialDurationFrame: {
					High: 480,
					Low: 330,
					Mid: 405,
				},
			},
			DistanceDamage: [
				{
					Damage: 530,
					Distance: 2.5,
				},
				{
					Damage: 350,
					Distance: 4,
				},
			],
			DirectDamage: 2200,
		},
		"2": {
			overwrites: {
				MaxFieldHP: {
					High: 28800,
					Low: 24000,
					Mid: 26400,
				},
				MaxHP: {
					High: 18432,
					Low: 15360,
					Mid: 16896,
				},
			},
		},
		"3": {
			overwrites: {
				InkConsume_Hook: {
					High: 0.0225,
					Low: 0.06,
					Mid: 0.0375,
				},
				InkConsume_PerSec: {
					High: 0.12,
					Low: 0.15,
					Mid: 0.1305,
				},
			},
			DistanceDamage: [
				{
					Damage: 450,
					Distance: 5.25,
				},
				{
					Damage: 350,
					Distance: 6,
				},
			],
		},
		"4": {
			overwrites: {
				TargetInCircleRadius: {
					High: 240,
					Low: 140,
					Mid: 190,
				},
			},
			DistanceDamage: [
				{
					Damage: 1500,
					Distance: 1.1,
				},
				{
					Damage: 500,
					Distance: 2.1,
				},
				{
					Damage: 300,
					Distance: 4.25,
				},
			],
		},
		"5": {
			overwrites: {
				SpawnSpeedZSpecUp: {
					High: 1.68,
					Low: 1.12,
					Mid: 1.4,
				},
				SpecialDurationFrame: {
					High: 600,
					Low: 480,
					Mid: 540,
				},
			},
			TickDamage: 4,
		},
		"6": {
			overwrites: {
				ChargeRateAutoPerFrame: {
					High: 0.01,
					Low: 0.002,
					Mid: 0.006,
				},
			},
			TickDamage: 33,
		},
		"7": {
			overwrites: {
				MaxFrame: {
					High: 216,
					Low: 160,
					Mid: 192,
				},
				MaxRadius: {
					High: 27,
					Low: 20,
					Mid: 24,
				},
			},
			DirectDamage: 300,
			WaveDamage: 450,
		},
		"8": {
			overwrites: {
				RadiusMax: {
					High: 4.3,
					Low: 3.3,
					Mid: 3.8,
				},
				RadiusMin: {
					High: 1.4,
					Low: 0.8,
					Mid: 1.1,
				},
			},
			ExhaleBlastParamMinChargeDistanceDamage: [
				{
					Damage: 2200,
					Distance: 6,
				},
			],
			ExhaleBlastParamMaxChargeDistanceDamage: [
				{
					Damage: 2200,
					Distance: 11,
				},
			],
		},
		"9": {
			overwrites: {
				SpecialDurationFrame: {
					High: 240,
					Low: 180,
					Mid: 220,
				},
			},
			TickDamage: 35,
		},
		"10": {
			overwrites: {
				DistanceDamageDistanceRate: {
					High: 1.3,
					Low: 1,
					Mid: 1.15,
				},
				SplashAroundVelocityMin: {
					High: 0.52,
					Low: 0.49,
					Mid: 0.505,
				},
				SplashAroundVelocityMax: {
					High: 0.35,
					Low: 0.33,
					Mid: 0.34,
				},
				SpecialDurationFrame: {
					High: 510,
					Low: 450,
					Mid: 480,
				},
				PaintRadius: {
					High: 3.9000000000000004,
					Mid: 3.865,
					Low: 3.83,
				},
			},
			DistanceDamage: [
				{
					Damage: 500,
					Distance: 2.55,
				},
				{
					Damage: 300,
					Distance: 5,
				},
			],
			DirectDamage: 1200,
		},
		"11": {
			overwrites: {
				SpecialDurationFrame: {
					High: 660,
					Low: 450,
					Mid: 570,
				},
			},
			SwingDamage: [
				{
					Damage: 1000,
					Distance: 0,
				},
				{
					Damage: 400,
					Distance: 4,
				},
			],
			ThrowDamage: [
				{
					Damage: 2200,
					Distance: 4,
				},
				{
					Damage: 600,
					Distance: 8,
				},
			],
			ThrowDirectDamage: 2200,
		},
		"12": {
			ArmorHP: 5000,
			overwrites: {
				SpecialDurationFrame: {
					High: 660,
					Low: 480,
					Mid: 570,
				},
			},
			BulletDamageMin: 160,
			BulletDamageMax: 320,
			CannonDamage: [
				{
					Damage: 500,
					Distance: 1,
				},
				{
					Damage: 300,
					Distance: 5.6,
				},
			],
			BumpDamage: 400,
		},
		"13": {
			overwrites: {
				DistanceDamageDistanceRate: {
					High: 1.2,
					Low: 1,
					Mid: 1.1,
				},
				PaintRadius: {
					High: 10.212,
					Mid: 9.36,
					Low: 8.51,
				},
				SplashAroundVelocityMin: {
					High: 0.7,
					Low: 0.6,
					Mid: 0.65,
				},
				SplashAroundVelocityMax: {
					High: 0.8,
					Low: 0.7,
					Mid: 0.75,
				},
			},
			DistanceDamage: [
				{
					Damage: 2200,
					Distance: 9,
				},
				{
					Damage: 700,
					Distance: 14.9,
				},
			],
		},
		"14": {
			overwrites: {
				SpawnSpeedZSpecUp: {
					High: 2.6,
					Low: 2,
					Mid: 2.3,
				},
			},
			TickDamage: 75,
		},
		"15": {
			overwrites: {
				PowerUpFrame: {
					High: 1500,
					Low: 1020,
					Mid: 1290,
				},
			},
		},
		"16": {
			overwrites: {
				CrossPaintCheckLength: {
					High: 3,
					Low: 2.5,
					Mid: 2.75,
				},
				CrossPaintRadius: {
					High: 3,
					Low: 2.5,
					Mid: 2.75,
				},
				DistanceDamageDistanceRate: {
					High: 1.2,
					Low: 1,
					Mid: 1.1,
				},
			},
			DistanceDamage: [
				{
					Damage: 700,
					Distance: 3.6,
				},
				{
					Damage: 350,
					Distance: 6,
				},
			],
		},
		"17": {
			overwrites: {
				SpecialDurationFrame: {
					High: 600,
					Low: 480,
					Mid: 540,
				},
			},
			DirectDamage: 1200,
			JumpDamage: 600,
		},
		"18": {
			overwrites: {
				DistanceDamageDistanceRate: {
					High: 1.1,
					Low: 1,
					Mid: 1.05,
				},
				PaintRadius: {
					High: 12,
					Low: 10,
					Mid: 11,
				},
			},
			DistanceDamage: [
				{
					Damage: 2200,
					Distance: 7,
				},
				{
					Damage: 600,
					Distance: 10.5,
				},
			],
		},
		"19": {
			overwrites: {
				SpawnSpeedZSpecUp: {
					High: 1.68,
					Low: 1.12,
					Mid: 1.4,
				},
				MoveSpeed: {
					High: 0.06,
					Low: 0.04,
					Mid: 0.053,
				},
			},
			DirectDamage: 400,
		},
	},
} as const;
